### YamlMime:PowershellCmdlet
summary: |-
  Adds an owner to an application.
module: Microsoft.Graph.Entra.Beta
notes: ""
links:
- text: Get-EntraBetaApplicationOwner
  href: Get-EntraBetaApplicationOwner.yml
- text: Remove-EntraBetaApplicationOwner
  href: Remove-EntraBetaApplicationOwner.yml
syntaxes:
- >-
  Add-EntraBetaApplicationOwner 
      -ObjectId <String> 
      -RefObjectId <String>
   [<CommonParameters>]
examples:
- title: 'Example 1: Add a user as an owner to an application'
  code: |-
    PS C:\> $ApplicationId = (Get-EntraBetaApplication -Top 1).ObjectId
    PS C:\> $UserObjectId = (Get-EntraBetaUser -Top 1).ObjectId
    PS C:\> Add-EntraBetaApplicationOwner -ObjectId $ApplicationId -RefObjectId $UserObjectId
  description: |-
    The first command gets an application using [Get-EntraBetaApplication](./Get-EntraBetaApplication.yml) cmdlet, and stores 
    the ObjectId property value in $ApplicationId variable.  

    The second command gets a user using [Get-EntraBetaUser](./Get-EntraBetaUser.yml) cmdlet, and stores 
    the ObjectId property value in $UserObjectId variable.  

    This final command adds an owner in $UserObjectId to an application in $ApplicationId.

    This command adds an owner to an application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of an application in Microsoft Entra ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: RefObjectId
  isRequired: true
  description: |+
    Specifies the ID of the Active Directory object to assign as owner/manager/member.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Add-EntraBetaApplicationOwner
name: Add-EntraBetaApplicationOwner
description: |-
  The Add-EntraBetaApplicationOwner cmdlet adds an owner to a Microsoft Entra ID application.
metadata:
  title: Add-EntraBetaApplicationOwner
  description: This article provides details on the Add-EntraBetaApplicationOwner command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/05/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
