### YamlMime:PowershellCmdlet
summary: |-
  The Add-EntraBetaApplicationPolicy cmdlet is not available at this time .
module: Microsoft.Graph.Entra.Beta
notes: ""
syntaxes:
- Add-EntraBetaApplicationPolicy -Id <String> -RefObjectId <String> [<CommonParameters>]
examples:
- title: 'Example 1: Add an application policy'
  code: |-
    PS C:\>Add-EntraBetaApplicationPolicy -ObjectId <object id of application> -RefObjectId <object id of policy>
  description: |-
    This command adds an application policy.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    The ID of the application for which you need to set the policy

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: RefObjectId
  isRequired: true
  description: |+
    Specifies the ID of the policy.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Add-EntraBetaApplicationPolicy
name: Add-EntraBetaApplicationPolicy
description: |-
  The Add-EntraBetaApplicationPolicy cmdlet adds an Azure Active Directory application policy.
metadata:
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
