### YamlMime:PowershellCmdlet
summary: |-
  Adds an owner for an application object.
module: Microsoft.Graph.Entra.Beta
notes: ""
inputs:
- name: <xref href="string" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Add-EntraBetaMSApplicationOwner -ObjectId <String> -RefObjectId <String> [<CommonParameters>]
examples:
- title: 'Example 1: Add an owner to an application'
  code: |-
    PS C:\>Add-EntraBetaMSApplicationOwner -ObjectId 3ddd22e7-a150-4bb3-b100-e410dea1cb84 -RefObjectId c13dd34a-492b-4561-b171-40fcce2916c5
  description: |-
    This command adds an owner to an application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique identifier of the object specific Azure Active Directory object

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: RefObjectId
  isRequired: true
  description: |+
    The unique identifier of the specific Azure Active Directory object that will be assigned as owner/manager/member

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Add-EntraBetaMSApplicationOwner
name: Add-EntraBetaMSApplicationOwner
description: |-
  Adds an owner for an application object.
metadata:
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
