### YamlMime:PowershellCmdlet
summary: |-
  The Get-EntraBetaApplicationProxyConnector cmdlet a list of all connectors, or if specified, details of a specific connector.
module: Microsoft.Graph.Entra.Beta
notes: |-
  ## RELATED LINKS
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    System.Nullable\`1\[\[System. Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\]\] System.Nullable\`1\[\[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\]\]
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-EntraBetaApplicationProxyConnector
   [-All] 
   [-Top <Int32>] 
   [-Filter <String>] 
   [<CommonParameters>]
- >-
  Get-EntraBetaApplicationProxyConnector 
   [-SearchString <String>] 
   [-All] 
   [<CommonParameters>]
- >-
  Get-EntraBetaApplicationProxyConnector 
   -Id <String> 
   [-All] 
   [<CommonParameters>]
examples:
- title: 'Example 1: Retrieve all connectors'
  code: |-
    PS C:\> Get-EntraBetaApplicationProxyConnector

    Name                           Value
    ----                           -----
    id                             147bd8b4-2134-4454-8f2a-1da81cf27917
    externalIp                     18.140.241.94
    machineName                    PERE-VARSHAM-FULLSTAK
    version                        1.5.3437.0
    status                         active
  description: |-
    This command Retrieve all connectors.
  summary: ""
- title: 'Example 2: Retrieve information for a specific connector'
  code: |-
    PS C:\> Get-EntraBetaApplicationProxyConnector -Id 147bd8b4-2134-4454-8f2a-1da81cf27917

    Name                           Value
    ----                           -----
    id                             147bd8b4-2134-4454-8f2a-1da81cf27917
    @odata.context                 https://graph.microsoft.com/beta/$metadata#onPrem...
    externalIp                     18.140.241.94
    version                        0.0
    machineName                    PERE-VARSHAM-FULLSTAK
    status                         active
  description: |-
    This example demonstrates how to Retrieve information for a specific connector.
  summary: ""
- title: 'Example 3: Retrieve information for a top one connector'
  code: |-
    PS C:\> Get-EntraBetaApplicationProxyConnector -Top 1

    Name                           Value
    ----                           -----
    id                             147bd8b4-2134-4454-8f2a-1da81cf27917
    externalIp                     18.140.241.94
    machineName                    PERE-VARSHAM-FULLSTAK
    version                        1.5.3437.0
    status                         active
  description: |-
    This example demonstrates how to Retrieve information for a top one connector.
  summary: ""
- title: 'Example 4: Retrieve information with SearchString parameter'
  code: |-
    PS C:\> Get-EntraBetaApplicationProxyConnector -SearchString "PERE-VARSHAM-FULLSTAK"

    Name                           Value
    ----                           -----
    id                             147bd8b4-2134-4454-8f2a-1da81cf27917
    externalIp                     18.140.241.94
    machineName                    PERE-VARSHAM-FULLSTAK
    version                        1.5.3437.0
    status                         active
  description: |-
    This example demonstrates how to Retrieve information using SearchString.
  summary: ""
- title: 'Example 5: Retrieve information using machineName property'
  code: |-
    PS C:\> Get-EntraBetaApplicationProxyConnector -Filter "machineName eq 'PERE-VARSHAM-FULLSTAK'"

    Name                           Value
    ----                           -----
    id                             147bd8b4-2134-4454-8f2a-1da81cf27917
    externalIp                     18.140.241.94
    machineName                    PERE-VARSHAM-FULLSTAK
    version                        1.5.3437.0
    status                         active
  description: |-
    This example demonstrates how to Retrieve information using machineName property.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: All
  description: |+
    List all pages.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Specifies an oData v3.0 filter statement.
    This parameter controls which objects are returned.
    Details on querying with oData can be found here: https://www.odata.org/documentation/odata-version-3-0/odata-version-3-0-core-protocol/#queryingcollections

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    The ID of the specific connector.
    You can find this ID by running the command without this parameter to get the desired ID, or by going into the portal and viewing connector details.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SearchString
  description: |+
    Specifies a search string.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Top
  description: |+
    Specifies the maximum number of records to return.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Get-EntraBetaApplicationProxyConnector
name: Get-EntraBetaApplicationProxyConnector
description: |-
  The Get-EntraBetaApplicationProxyConnector cmdlet retrieves the details for a given connector.
  If no connectorId is specified, it retrieves all the connectors assigned to the tenant.
metadata:
  title: Get-EntraBetaApplicationProxyConnector
  description: This article provides details on the Get-EntraBetaApplicationProxyConnector command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 04/09/2023
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
