### YamlMime:PowershellCmdlet
summary: |-
  The Get-EntraBetaApplicationProxyApplicationConnectorGroup cmdlet retrieves the connector group assigned for a specific application.
module: Microsoft.Graph.Entra.Beta
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-EntraBetaApplicationProxyApplicationConnectorGroup 
   -ObjectId <String> 
   [<CommonParameters>]
examples:
- title: 'Example 1: retrieves the connector group assigned for the specified application'
  code: |-
    PS C:\> Get-EntraBetaApplicationProxyApplicationConnectorGroup -ObjectId 9509afde-b5a9-4adf-b767-4f46c472c36a

    Id                                   Name       ConnectorGroupType IsDefault
    --                                   ----       ------------------ ---------
    87ffe1e2-6313-4a22-93eb-da1eb8a2bf8d test-group applicationProxy       False
  description: |-
    This command retrieves the connector group assigned for the specified application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    ObjectId is the ID of the application.
    This ObjectId can be found using the Get-EntraBetaApplication command.
    You can also find this ObjectId in the Microsoft Portal by navigating to Microsoft Entra ID, Enterprise Applications, All Applications, Select your application, go to the properties tab, and use the ObjectId on that page.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Get-EntraBetaApplicationProxyApplicationConnectorGroup
name: Get-EntraBetaApplicationProxyApplicationConnectorGroup
description: |-
  The Get-EntraBetaApplicationProxyApplicationConnectorGroup cmdlet retrieves the connector group assigned for the specified application.
  The application must be configured for Application Proxy in Microsoft Entra ID.
metadata:
  title: Get-EntraBetaApplicationProxyApplicationConnectorGroup
  description: This article provides details on the Get-EntraBetaApplicationProxyApplicationConnectorGroup.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 04/11/2023
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
