### YamlMime:PowershellCmdlet
summary: |-
  The Get-EntraBetaApplicationProxyApplication cmdlet retrieves an application configured for Application Proxy in Microsoft Entra ID.
module: Microsoft.Graph.Entra.Beta.Get-EntraBetaApplicationProxyApplication
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-EntraBetaApplicationProxyApplication 
   -ObjectId <String> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Retrieves an application configured for Application Proxy'
  code: |-
    PS C:\> Get-EntraBetaApplicationProxyApplication -ObjectId 61ec5727-7d0b-40b3-bd4e-817076b540fa

    AlternateUrl ApplicationServerTimeout ApplicationType ExternalAuthenticationType ExternalUrl
    ------------ ------------------------ --------------- -------------------------- -----------
                 Long                     enterpriseapp   aadPreAuthentication      
    https://testp-m365x99297270.msapppr...
  description: |-
    This command Retrieves an application configured for Application Proxy.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    This ObjectId is the unique application ID of the application.
    This ObjectId can be found using the Get-AzureADApplication command.
    You can also find ObjectId in the Microsoft Portal by navigating to Microsoft Entra ID, Enterprise Applications, All Applications, Select your application, go to the properties tab, and use the ObjectId on that page.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Get-EntraBetaApplicationProxyApplication.
name: Get-EntraBetaApplicationProxyApplication.
description: |-
  The Get-EntraBetaApplicationProxyApplication cmdlet retrieves an application configured for Application Proxy in Microsoft Entra ID.
metadata:
  title: Get-EntraBetaApplicationProxyApplication.
  description: This article provides details on the Get-EntraBetaApplicationProxyApplication.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 04/11/2023
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
