### YamlMime:PowershellCmdlet
summary: |-
  Gets an application policy.
module: Microsoft.Graph.Entra.Beta
notes: ""
syntaxes:
- Get-EntraBetaApplicationPolicy -Id <String> [<CommonParameters>]
examples:
- title: 'Example 1: Get an application policy'
  code: |-
    PS C:\>Get-EntraBetaApplicationPolicy -Id "<object id of application>"
  description: |-
    This command gets the specified application policy.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    The ID of the application for which you need to retrieve the policy

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Get-EntraBetaApplicationPolicy
name: Get-EntraBetaApplicationPolicy
description: |-
  The Get-EntraBetaApplicationPolicy cmdlet gets an Azure Active Directory application policy.
metadata:
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
