### YamlMime:PowershellCmdlet
summary: |-
  Retrieves the list of owners for an application object.
module: Microsoft.Graph.Entra.Beta
notes: ""
inputs:
- name: <xref href="bool?" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="int?" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="string" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Open.MSGraph.Model.GetDirectoryObjectsResponse" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Get-EntraBetaMSApplicationOwner [-ObjectId <String>] [-All] [-Top <Int32>] [<CommonParameters>]
examples:
- title: 'Example 1: Get the owner of an application'
  code: |-
    PS C:\>Get-EntraBetaMSApplicationOwner -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -Top 1

              ObjectId                             ObjectType
              --------                             ----------
              c13dd34a-492b-4561-b171-40fcce2916c5 User
  description: |-
    This command gets the owner of an application.
  summary: ""
- title: 'Example 1: Get the owners of an application'
  code: |-
    PS C:\>Get-EntraBetaMSApplicationOwner -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -All

              ObjectId                             ObjectType
              --------                             ----------
              c13dd34a-492b-4561-b171-40fcce2916c5 User
  description: |-
    This command gets the owners of an application.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: All
  description: |+
    List all pages.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  description: |+
    Specifes the ID of an application in Azure Active Directory.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Top
  description: |+
    Specifies the maximum number of records to return.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Get-EntraBetaMSApplicationOwner
name: Get-EntraBetaMSApplicationOwner
description: |-
  Retrieves the list of owners for an application object.
metadata:
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
