### YamlMime:PowershellCmdlet
summary: |-
  Gets the key credentials for an application.
module: Microsoft.Graph.Entra.Beta
notes: ""
links:
- text: New-EntraBetaApplicationKeyCredential
  href: New-EntraBetaApplicationKeyCredential.yml
- text: Remove-EntraBetaApplicationKeyCredential
  href: Remove-EntraBetaApplicationKeyCredential.yml
syntaxes:
- >-
  Get-EntraBetaApplicationKeyCredential 
      -ObjectId <String>
   [<CommonParameters>]
examples:
- title: 'Example 1: Get key credentials'
  code: |-
    PS C:\> Get-EntraBetaApplicationKeyCredential -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84"

    CustomKeyIdentifier : {116, 101, 115, 116}
    EndDate             : 10/23/2024 11:36:56 AM
    KeyId               : 52ab6cca-bc59-4f06-8450-75a3d2b8e53b
    StartDate           : 11/22/2023 11:35:16 AM
    Type                : Symmetric
    Usage               : Sign
    Value               :

    CustomKeyIdentifier : {84, 101, 115, 116}
    EndDate             : 10/23/2024 9:46:49 AM
    KeyId               : 2e5143ee-9912-40c1-8c6a-a84f8124a6af
    StartDate           : 10/23/2023 9:46:48 AM
    Type                : Symmetric
    Usage               : Sign
    Value               :
  description: |-
    This command gets the key credentials for the specified application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies a unique ID of an application in Microsoft Entra ID for which to get key credentials

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Get-EntraBetaApplicationKeyCredential
name: Get-EntraBetaApplicationKeyCredential
description: |-
  The **Get-EntraBetaApplicationKeyCredential** cmdlet gets the key credentials for an application.
metadata:
  title: Get-EntraBetaApplicationKeyCredential
  description: This article provides details on the Get-EntraBetaApplicationKeyCredential command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/04/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
