### YamlMime:PowershellCmdlet
summary: |-
  The Get-EntraBetaApplicationProxyConnectorMemberOf command gets the ConnectorGroup that the specified Connector is a member of.
module: Microsoft.Graph.Entra.Beta
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-EntraBetaApplicationProxyConnector
  href: Get-EntraBetaApplicationProxyConnector.yml
syntaxes:
- >-
  Get-EntraBetaApplicationProxyConnectorMemberOf
   -Id <String> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Gets ConnectorGroup With Specified Connector ID.'
  code: |-
    PS C:\> Get-EntraBetaApplicationProxyConnectorMemberOf -Id 147bd8b4-2134-4454-8f2a-1da81cf27917

    Name                           Value
    ----                           -----
    id                             87ffe1e2-6313-4a22-93eb-da1eb8a2bf8d
    region
    connectorGroupType             applicationProxy
    isDefault                      False
    name                           test-group
  description: |-
    This command gets the ConnectorGroup With Specified Connector ID.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    The ID of the connector. You can find ID by running Get-EntraBetaApplicationProxyConnector.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Get-EntraBetaApplicationProxyConnectorMemberOf
name: Get-EntraBetaApplicationProxyConnectorMemberOf
description: |-
  The Get-EntraBetaApplicationProxyConnectorMemberOf command gets the ConnectorGroup that the specified Connector is a member of.
  If no group is assigned to the connector, by default it is in 'Default.'
metadata:
  title: Get-EntraBetaApplicationProxyConnectorMemberOf
  description: This article provides details on the Get-EntraBetaApplicationProxyConnectorMemberOf command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 04/15/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
