### YamlMime:PowershellCmdlet
summary: |-
  Gets the owner of an application.
module: Microsoft.Graph.Entra.Beta
notes: ""
syntaxes:
- Get-EntraBetaApplicationOwner [-Top <Int32>] -ObjectId <String> [-All] [<CommonParameters>]
examples:
- title: 'Example 1: Get the owner of an application'
  code: |-
    PS C:\>Get-EntraBetaApplicationOwner -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84"

    ObjectId                             ObjectType
    --------                             ----------
    c13dd34a-492b-4561-b171-40fcce2916c5 User
  description: |-
    This command gets the owner of an application.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: All
  description: |+
    List all pages.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifes the ID of an application in Azure Active Directory.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Top
  description: |+
    Specifies the maximum number of records to return.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Get-EntraBetaApplicationOwner
name: Get-EntraBetaApplicationOwner
description: |-
  The Get-EntraBetaApplicationOwner cmdlet get an owner of an Azure Active Directory application.
metadata:
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
