### YamlMime:PowershellCmdlet
summary: |-
  Retrieves settings for a federated domain.
module: Microsoft.Graph.Entra.Beta
notes: ""
outputs:
- name: <xref href="Microsoft.Online.Administration.DomainFederationSettings" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="This cmdlet returns the following settings:" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="ActiveLogOnUri" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="FederationBrandName" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="IssuerUri" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="LogOffUri" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="MetadataExchangeUri" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="NextSigningCertificate" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="PassiveLogOnUri" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="SigningCertificate" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Get-EntraBetaDomainFederationSettings [-DomainName] <String> [[-TenantId] <Guid>] [<CommonParameters>]
examples:
- title: EXAMPLE 1
  code: "Get-EntraBetaDomainFederationSettings -DomainName contoso.com\r\n    \r\n    Returns the federation settings for contoso.com.\r\n    Description\r\n    \r\n    -----------\r\n    \r\n    Returns the federation settings for contoso.com."
  description: ""
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DomainName
  isRequired: true
  description: |+
    The fully qualified domain name to retrieve.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: TenantId
  description: |+
    The unique ID of the tenant to perform the operation on.
    If this is not provided then the value will default to the tenant of the current user.
    This parameter is only applicable to partner users.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Get-EntraBetaDomainFederationSettings
name: Get-EntraBetaDomainFederationSettings
description: |-
  The Get-EntraBetaDomainFederationSettings cmdlet gets key settings from Microsoft Azure Active Directory.
  Use the Get-EntraFederationProperty cmdlet to get settings for both Microsoft Azure Active Directory and the Active Directory Federation Services server.
metadata:
  external help file: Microsoft.Graph.Entra.Beta-help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
