### YamlMime:PowershellCmdlet
summary: |-
  The Get-EntraBetaApplicationProxyConnectorGroup cmdlet retrieves a list of all connector groups, or if specified, details of a specific connector group.
module: Microsoft.Graph.Entra.Beta.Get-EntraBetaApplicationProxyConnectorGroup
notes: |-
  ## RELATED LINKS
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    System.Nullable\`1\[\[System. Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\]\] System.Nullable\`1\[\[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\]\]
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-EntraBetaApplicationProxyConnectorGroup 
   [-All] 
   [-Top <Int32>] 
   [-Filter <String>]
   [<CommonParameters>]
- >-
  Get-EntraBetaApplicationProxyConnectorGroup 
   [-SearchString <String>] 
   [-All] 
   [<CommonParameters>]
- >-
  Get-EntraBetaApplicationProxyConnectorGroup
   -Id <String> 
   [-All] 
   [<CommonParameters>]
examples:
- title: 'Example 1: Retrieve all connector groups'
  code: |-
    PS C:\> Get-EntraBetaApplicationProxyConnectorGroup

    Name                           Value
    ----                           -----
    id                             5ce15799-97a5-4e45-add2-2094c8cd3752
    region                         eur
    connectorGroupType             applicationProxy
    isDefault                      True
    name                           Default

    id                             b69debb1-6431-4c66-92c8-547990641283
    region                         eur
    connectorGroupType             applicationProxy
    isDefault                      False
    name                           test1
  description: |-
    This command Retrieve all connector groups.
  summary: ""
- title: 'Example 2: Retrieve a specific connector group'
  code: |-
    PS C:\> Get-EntraBetaApplicationProxyConnectorGroup -Id 5ce15799-97a5-4e45-add2-2094c8cd3752

    Name                           Value
    ----                           -----
    id                             5ce15799-97a5-4e45-add2-2094c8cd3752
    @odata.context                 https://graph.microsoft.com/beta/$metadata#onPremisesPublishingProfiles('applicationProxy')/connectorGroups/$entity
    isDefault                      True
    name                           Default
    region                         eur
    connectorGroupType             applicationProxy
  description: |-
    This command Retrieve a specific connector group.
  summary: ""
- title: 'Example 3: Retrieve Top one connector groups'
  code: |-
    PS C:\> Get-EntraBetaApplicationProxyConnectorGroup -Top 1

    Name                           Value
    ----                           -----
    id                             5ce15799-97a5-4e45-add2-2094c8cd3752
    @odata.context                 https://graph.microsoft.com/beta/$metadata#onPremisesPublishingProfiles('applicationProxy')/connectorGroups/$entity
    isDefault                      True
    name                           Default
    region                         eur
    connectorGroupType             applicationProxy
  description: |-
    This command Retrieve top one connector groups.
  summary: ""
- title: 'Example 4: Retrieve a connector groups with filter parameter.'
  code: |-
    PS C:\> Get-EntraBetaApplicationProxyConnectorGroup -Filter "name eq 'Default'"

    Name                           Value
    ----                           -----
    id                             5ce15799-97a5-4e45-add2-2094c8cd3752
    region                         eur
    connectorGroupType             applicationProxy
    isDefault                      True
    name                           Default
  description: |-
    This command Retrieve a connector groups with filter parameter.
  summary: ""
- title: Example 5:Retrieve a connector groups with String parameter
  code: |-
    PS C:\> Get-EntraBetaApplicationProxyConnectorGroup -SearchString "test"

    Name                           Value
    ----                           -----
    id                             b69debb1-6431-4c66-92c8-547990641283
    region                         eur
    connectorGroupType             applicationProxy
    isDefault                      False
    name                           test1
  description: |-
    This command Retrieve a connector groups with String parameter.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: All
  description: |+
    List all pages.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Specifies an oData v3.0 filter statement.
    This parameter controls which objects are returned.
    Details on querying with oData can be found here: https://www.odata.org/documentation/odata-version-3-0/odata-version-3-0-core-protocol/#queryingcollections

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    The ID of the specific connector group.
    You can find this ID by running the command without this parameter to get the desired ID, or by going into the portal and viewing connector group details.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SearchString
  description: |+
    Specifies the search string.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Top
  description: |+
    Specifies the maximum number of records to return.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Get-EntraBetaApplicationProxyConnectorGroup.
name: Get-EntraBetaApplicationProxyConnectorGroup.
description: |-
  The Get-EntraBetaApplicationProxyConnectorGroup cmdlet retrieves a list of all connector groups, or if specified, details of the specified connector group.
metadata:
  title: Get-EntraBetaApplicationProxyConnectorGroup.
  description: This article provides details on the Get-EntraBetaApplicationProxyConnectorGroup.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 04/15/2023
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
