### YamlMime:PowershellCmdlet
summary: |-
  Creates an application.
module: Microsoft.Graph.Entra.Beta
notes: ""
links:
- text: Get-EntraBetaApplication
  href: Get-EntraBetaApplication.yml
- text: Remove-EntraBetaApplication
  href: Remove-EntraBetaApplication.yml
- text: Set-EntraBetaApplication
  href: Set-EntraBetaApplication.yml
syntaxes:
- >-
  New-EntraBetaApplication 
      -DisplayName <String> 
      [-AddIns <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.AddIn]>]
      [-SignInAudience <String>] 
      [-Oauth2AllowImplicitFlow <Boolean>]
      [-ReplyUrls <System.Collections.Generic.List`1[System.String]>] 
      [-WwwHomepage <String>] 
      [-IsDisabled <Boolean>] 
      [-AllowGuestsSignIn <Boolean>] 
      [-PublisherDomain <String>]
      [-OrgRestrictions <System.Collections.Generic.List`1[System.String]>] 
      [-OptionalClaims <OptionalClaims>]
      [-ParentalControlSettings <ParentalControlSettings>] 
      [-Oauth2AllowUrlPathMatching <Boolean>]
      [-KeyCredentials <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.KeyCredential]>]
      [-IdentifierUris <System.Collections.Generic.List`1[System.String]>] 
      [-GroupMembershipClaims <String>]
      [-Oauth2Permissions <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.OAuth2Permission]>]
      [-LogoutUrl <String>] 
      [-ErrorUrl <String>] 
      [-SamlMetadataUrl <String>] 
      [-IsDeviceOnlyAuthSupported <Boolean>]
      [-PreAuthorizedApplications <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.PreAuthorizedApplication]>]
      [-AvailableToOtherTenants <Boolean>]
      [-KnownClientApplications <System.Collections.Generic.List`1[System.String]>]
      [-AllowPassthroughUsers <Boolean>]
      [-RequiredResourceAccess <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.RequiredResourceAccess]>]
      [-PublicClient <Boolean>] 
      [-RecordConsentConditions <String>] 
      [-Oauth2RequirePostResponse <Boolean>]
      [-AppLogoUrl <String>]
      [-PasswordCredentials <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.PasswordCredential]>]
      [-Homepage <String>] 
      [-AppRoles <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.AppRole]>]
      [-InformationalUrls <InformationalUrl>] 
   [<CommonParameters>]
examples:
- title: 'Example 1: Create an application'
  code: |-
    PS C:\>New-EntraBetaApplication -DisplayName "My new application"

    ObjectId                             AppId                                DisplayName 
    --------                             -----                                ----------- 
    acd10942-5747-4385-8824-4c5d5fa904f9 b5fecfab-0ea2-4fd1-8570-b2c41b3d5149 My new application
  description: |-
    This command creates an application in Microsoft Entra ID.
  summary: ""
- title: "Example 2: Create an application with '-IdentifierUris' parameter"
  code: |-
    PS C:\>New-EntraBetaApplication -DisplayName "My new application" -IdentifierUris "https://mynewapp.contoso.com"

    ObjectId                             AppId                                DisplayName 
    --------                             -----                                ----------- 
    acd10942-5747-4385-8824-4c5d5fa904f9 b5fecfab-0ea2-4fd1-8570-b2c41b3d5149 My new application
  description: |-
    This example shows how to create an application having **-IdentifierUris** parameter.  

    This command creates an application in Microsoft Entra ID.
  summary: ""
- title: "Example 3: Create an application with '-HomePage' parameter"
  code: |-
    PS C:\>New-EntraBetaApplication -DisplayName "My new application" -HomePage "https://mynewapp.home.com"

    ObjectId                             AppId                                DisplayName 
    --------                             -----                                ----------- 
    acd10942-5747-4385-8824-4c5d5fa904f9 b5fecfab-0ea2-4fd1-8570-b2c41b3d5149 My new application
  description: |-
    This example shows how to create an application having **-HomePage** parameter.  

    This command creates an application in Microsoft Entra ID.
  summary: ""
- title: "Example 4: Create an application with '-LogoutUrl' parameter"
  code: |-
    PS C:\>New-EntraBetaApplication -DisplayName "My new application" -LogoutUrl "https://mynewapp.com/logout.aspx"

    ObjectId                             AppId                                DisplayName 
    --------                             -----                                ----------- 
    acd10942-5747-4385-8824-4c5d5fa904f9 b5fecfab-0ea2-4fd1-8570-b2c41b3d5149 My new application
  description: |-
    This example shows how to create an application having **-LogoutUrl** parameter.  

    This command creates an application in Microsoft Entra ID.
  summary: ""
- title: "Example 5: Create an application with '-IsDeviceOnlyAuthSupported' parameter"
  code: |-
    PS C:\>New-EntraBetaApplication -DisplayName "My new application" -IsDeviceOnlyAuthSupported $false

    ObjectId                             AppId                                DisplayName 
    --------                             -----                                ----------- 
    acd10942-5747-4385-8824-4c5d5fa904f9 b5fecfab-0ea2-4fd1-8570-b2c41b3d5149 My new application
  description: |-
    This example shows how to create an application having **-IsDeviceOnlyAuthSupported** parameter.  

    This command creates an application in Microsoft Entra ID.
  summary: ""
parameters:
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.AddIn" data-throw-if-not-resolved="False" /><span>]</span>
  name: AddIns
  description: |+
    Defines custom behavior that a consuming service can use to call an app in specific contexts.
    For example, applications that can render file streams might set the addIns property for its "FileHandler" functionality.
    This lets services like Office 365 call the application in the context of a document the user is working on.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowGuestsSignIn
  description: |+
    Sets a property on the application to indicate if the application accepts other IDPs or not or partially accepts.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowPassthroughUsers
  description: |+
    Sets indicate that the application supports pass through users who have no presence in the resource tenant.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AppLogoUrl
  description: |+
    Sets the url for the application logo image stored in a CDN.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.AppRole" data-throw-if-not-resolved="False" /><span>]</span>
  name: AppRoles
  description: |+
    The collection of application roles that an application might declare.
    These roles can be assigned to users, groups, or service principals.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AvailableToOtherTenants
  description: |+
    Indicates whether this application is available in other tenants.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayName
  isRequired: true
  description: |+
    Specifies the display name of the application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ErrorUrl
  description: |+
    The Error URL of this application

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GroupMembershipClaims
  description: |+
    A bitmask that configures the "groups" claim issued in a user or OAuth 2.0 access token that the application expects.
    The bitmask values are: 0: None, 1: Security groups and Microsoft Entra ID roles, 2: Reserved, and 4: Reserved.
    Setting the bitmask to 7 gets all of the security groups, distribution groups, and Microsoft Entra ID roles that the signed-in user is a member of.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Homepage
  description: |+
    The URL to the application's homepage.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: IdentifierUris
  description: |+
    User-defined URIs that uniquely identify a Web application within its Microsoft Entra ID tenant, or within a verified custom domain (see "Domains" tab in the Azure classic portal) if the application is multitenant.

    The first element is populated from the Web application's "APP ID URI" field if updated via the Azure classic portal (or respective Microsoft Entra ID PowerShell cmdlet parameter).
    More URIs can be added via the application manifest; see Understanding the Microsoft Entra ID Application Manifest for details.
    This collection is also used to populate the Web application's servicePrincipalNames collection.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="InformationalUrl" data-throw-if-not-resolved="False" />
  name: InformationalUrls
  description: |+
    Basic profile information of the application such as app's marketing, support, terms of service and privacy statement URLs. The terms of service and privacy statement are surfaced to users through the user consent experience.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsDeviceOnlyAuthSupported
  description: |+
    Specifies if the application supports authentication using a device token.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsDisabled
  description: |+
    Enables or disables the application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.KeyCredential" data-throw-if-not-resolved="False" /><span>]</span>
  name: KeyCredentials
  description: |+
    The collection of key credentials associated with the application

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: KnownClientApplications
  description: |+
    Client applications that are tied to this resource application.
    Consent to any of the known client applications result in implicit consent to the resource application through a combined consent dialog (showing the OAuth permission scopes required by the client and the resource).

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: LogoutUrl
  description: |+
    The logout url for this application

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Oauth2AllowImplicitFlow
  description: |+
    Specifies whether this web application can request OAuth2.0 implicit flow tokens.
    The default is false.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Oauth2AllowUrlPathMatching
  description: |+
    Specifies whether, as part of OAuth 2.0 token requests, Microsoft Entra ID allows path matching of the redirect URI against the application's replyUrls.
    The default is false.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.OAuth2Permission" data-throw-if-not-resolved="False" /><span>]</span>
  name: Oauth2Permissions
  description: |+
    The collection of OAuth 2.0 permission scopes that the web API (resource) application exposes to client applications.
    These permission scopes might be granted to client applications during consent.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Oauth2RequirePostResponse
  description: |+
    Set this variable to true if an Oauth2 post response is required.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="OptionalClaims" data-throw-if-not-resolved="False" />
  name: OptionalClaims
  description: |+
    Application developers can configure optional claims in their Microsoft Entra ID apps to specify which claims they want in tokens sent to their application by the Microsoft security token service.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: OrgRestrictions
  description: |+
    Sets a list of tenants allowed to access application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ParentalControlSettings" data-throw-if-not-resolved="False" />
  name: ParentalControlSettings
  description: |+
    Specifies parental control settings for an application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.PasswordCredential" data-throw-if-not-resolved="False" /><span>]</span>
  name: PasswordCredentials
  description: |+
    The collection of password credentials associated with the application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.PreAuthorizedApplication" data-throw-if-not-resolved="False" /><span>]</span>
  name: PreAuthorizedApplications
  description: |+
    Sets list of pre-authorized applications.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: PublicClient
  description: |+
    Specifies whether this application is a public client (such as an installed application running on a mobile device).
    Default is false.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PublisherDomain
  description: |+
    Sets reliable domain, which can be used to identify an application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: RecordConsentConditions
  description: |+
    Don't use.
    Might be removed in future versions.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: ReplyUrls
  description: |+
    Specifies the URLs that user tokens are sent to for sign in, or the redirect URIs that OAuth 2.0 authorization codes and access tokens are sent to.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.RequiredResourceAccess" data-throw-if-not-resolved="False" /><span>]</span>
  name: RequiredResourceAccess
  description: |+
    Specifies resources that this application requires access to and the set of OAuth permission scopes and application roles that it needs under each of those resources.
    This preconfiguration of required resource access drives the consent experience.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SamlMetadataUrl
  description: |+
    The URL to the SAML metadata for the application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SignInAudience
  description: |+
    Sets audience for signing in to the application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: WwwHomepage
  description: |+
    Sets the primary Web page.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.New-EntraBetaApplication
name: New-EntraBetaApplication
description: |-
  The New-EntraBetaApplication cmdlet creates an application in Microsoft Entra ID.
metadata:
  title: New-EntraBetaApplication
  description: This article provides details on the New-EntraBetaApplication command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/05/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
