### YamlMime:PowershellCmdlet
summary: |-
  The New-EntraBetaApplicationProxyConnectorGroup cmdlet creates a new Application Proxy Connector group.
module: Microsoft.Graph.Entra.Beta
notes: ""
inputs:
- name: <xref href="Microsoft.Open.MSGraph.Model.Name" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  New-EntraBetaApplicationProxyConnectorGroup
   -Name <Name> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Create a new Connector Group.'
  code: |-
    PS C:\> New-EntraBetaApplicationProxyConnectorGroup -Name "Backup Application Servers"

    Name                           Value
    ----                           -----
    id                             55311d30-74d7-4cad-a7d7-f8d76e110345
    @odata.context                 https://graph.microsoft.com/beta/$metadata#onPremisesPublishingProfiles('applicationProxy')/connectorGroups/$entity
    isDefault                      False
    name                           Backup Application Servers
    region                         eur
    connectorGroupType             applicationProxy
  description: |-
    This Command Create a new Connector Group with the name "Backup Application Servers"
  summary: ""
parameters:
- type: <xref href="Name" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    The name of the new Connector Group.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.New-EntraBetaApplicationProxyConnectorGroup
name: New-EntraBetaApplicationProxyConnectorGroup
description: |-
  The New-EntraBetaApplicationProxyConnectorGroup cmdlet creates a new Application Proxy connector group.
metadata:
  title: New-EntraBetaApplicationProxyConnectorGroup
  description: This article provides details on the New-EntraBetaApplicationProxyConnectorGroupcommand.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 04/05/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
