### YamlMime:PowershellCmdlet
summary: |-
  Creates an application extension property.
module: Microsoft.Graph.Entra.Beta
notes: ""
syntaxes:
- >-
  New-EntraBetaApplicationExtensionProperty -ObjectId <String> [-DataType <String>] [-Name <String>]
   [-TargetObjects <System.Collections.Generic.List`1[System.String]>] [<CommonParameters>]
examples:
- title: 'Example 1: Create an extension property'
  code: |-
    PS C:\>New-EntraBetaApplicationExtensionProperty -ObjectID "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -DataType "string" -Name "NewAttribute"


    ObjectId                             Name                                                    TargetObjects
    --------                             ----                                                    -------------
    3ddd22e7-a150-4bb3-b100-e410dea1cb84 extension_36ee4c6c081240a2b820b22ebd02bce3_NewAttribute {}
  description: |-
    This command creates an application extension property of the string type for the specified object.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DataType
  description: |+
    Specifies the data type of the extension property.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies the data type of the extension property.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies a unique ID of an application in Azure Active Directory.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: TargetObjects
  description: |+
    Specifies target objects.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.New-EntraBetaApplicationExtensionProperty
name: New-EntraBetaApplicationExtensionProperty
description: |-
  The New-EntraBetaApplicationExtensionProperty cmdlet creates an application extension property for an object in Azure Active Directory.
metadata:
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
