### YamlMime:PowershellCmdlet
summary: |-
  Creates a password credential for an application.
module: Microsoft.Graph.Entra.Beta
notes: ""
syntaxes:
- >-
  New-EntraBetaApplicationPasswordCredential [-CustomKeyIdentifier <String>] [-Value <String>]
   [-EndDate <DateTime>] -ObjectId <String> [-StartDate <DateTime>] [<CommonParameters>]
examples:
- title: 'Example 1: Create a password credential'
  code: |-
    PS C:\>New-EntraBetaApplicationPasswordCredential -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84"

    CustomKeyIdentifier :
    EndDate             : 9/28/2017 3:57:10 PM
    KeyId               :
    StartDate           : 9/28/2016 3:57:10 PM
    Value               : SAMPLE_KEY_VALUE
  description: ""
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CustomKeyIdentifier
  description: |+
    @{Text=}

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: EndDate
  description: |+
    @{Text=}

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of a user in Azure AD.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: StartDate
  description: |+
    @{Text=}

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Value
  description: |+
    @{Text=}

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.New-EntraBetaApplicationPasswordCredential
name: New-EntraBetaApplicationPasswordCredential
description: |-
  The New-EntraBetaApplicationPasswordCredential cmdlet creates a password credential for an application in Azure Active Directory (AD).
metadata:
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
