### YamlMime:PowershellCmdlet
summary: |-
  Removes an application extension property.
module: Microsoft.Graph.Entra.Beta
notes: ""
syntaxes:
- >-
  Remove-EntraBetaApplicationExtensionProperty -ObjectId <String> -ExtensionPropertyId <String>
   [<CommonParameters>]
examples:
- title: 'Example 1: Remove an extension property'
  code: |-
    PS C:\> Remove-EntraBetaApplicationExtensionProperty -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -ExtensionPropertyId "344ed560-f8e7-410e-ab9f-c79df5c36"
  description: |-
    This command removes the extension property that has the specified ID from an application in Azure Active Directory.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ExtensionPropertyId
  isRequired: true
  description: |+
    Specifies the unique ID of the extension property to remove.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the unique ID of an application in Azure Active Directory.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Remove-EntraBetaApplicationExtensionProperty
name: Remove-EntraBetaApplicationExtensionProperty
description: |-
  The Remove-EntraBetaApplicationExtensionProperty cmdlet removes an application extension property for an object in Azure Active Directory.
metadata:
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
