### YamlMime:PowershellCmdlet
summary: |-
  Removes an application policy.
module: Microsoft.Graph.Entra.Beta
notes: ""
syntaxes:
- Remove-EntraBetaApplicationPolicy -Id <String> -PolicyId <String> [<CommonParameters>]
examples:
- title: 'Example 1: Remove an application policy'
  code: |-
    PS C:\>Remove-EntraBetaApplicationPolicy -ObjectId <object id of application> -PolicyId <object id of policy>
  description: |-
    This command removes the specified application policy.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    {{Fill Id Description}}

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PolicyId
  isRequired: true
  description: |+
    Specifies the ID of the policy.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Remove-EntraBetaApplicationPolicy
name: Remove-EntraBetaApplicationPolicy
description: |-
  The Remove-EntraBetaApplicationPolicy cmdlet removes an application policy from Azure Active Directory (AD).
metadata:
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
