### YamlMime:PowershellCmdlet
summary: |-
  Removes an owner from an application.
module: Microsoft.Graph.Entra.Beta
notes: ""
links:
- text: Add-EntraBetaApplicationOwner
  href: Add-EntraBetaApplicationOwner.yml
- text: Get-EntraBetaApplicationOwner
  href: Get-EntraBetaApplicationOwner.yml
syntaxes:
- >-
  Remove-EntraBetaApplicationOwner 
      -OwnerId <String> 
      -ObjectId <String> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Remove an owner from an application'
  code: |-
    PS C:\>Remove-EntraBetaApplicationOwner -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -OwnerId "c13dd34a-492b-4561-b171-40fcce2916c5"
  description: |-
    This command removes the specified owner from the specified application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of an application in Microsoft Entra ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: OwnerId
  isRequired: true
  description: |+
    Specifies the ID of the owner.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Remove-EntraBetaApplicationOwner
name: Remove-EntraBetaApplicationOwner
description: |-
  The Remove-EntraBetaApplicationOwner cmdlet removes an owner from an application in Microsoft Entra ID.
metadata:
  title: Remove-EntraBetaApplicationOwner
  description: This article provides details on the Remove-EntraBetaApplicationOwner command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/05/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
