### YamlMime:PowershellCmdlet
summary: |-
  Removes a key credential from an application.
module: Microsoft.Graph.Entra.Beta
notes: ""
syntaxes:
- Remove-EntraBetaApplicationKeyCredential -ObjectId <String> -KeyId <String>[<CommonParameters>]
examples:
- title: 'Example 1: Remove a key credential'
  code: |-
    PS C:\> Remove-EntraBetaApplicationKeyCredential -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -KeyId "6aa971c6-3040-45df-87ed-581c8c09ff2b"
  description: |-
    This command removes the specified key credential from the specified application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: KeyId
  isRequired: true
  description: |+
    Specifies a custom key ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies a unique ID of an application in Azure Active Directory.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Remove-EntraBetaApplicationKeyCredential
name: Remove-EntraBetaApplicationKeyCredential
description: |-
  The Remove-EntraBetaApplicationKeyCredential cmdlet removes a key credential from an application.
metadata:
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
