### YamlMime:PowershellCmdlet
summary: |-
  Deletes an Application Proxy application.
module: Microsoft.Graph.Entra.Beta
notes: ""
links:
- text: Get-EntraBetaApplication
  href: Get-EntraBetaApplication.yml
syntaxes:
- >-
  Remove-EntraBetaApplicationProxyApplication 
   -ObjectId <String> 
   [-RemoveADApplication <Boolean>]
   [<CommonParameters>]
examples:
- title: 'Example 1: Remove a Proxy Application'
  code: |-
    PS C:\> Remove-EntraBetaApplicationProxyApplication -ObjectId 257098d1-f8dd-4efb-88a2-1c92d3654f10
  description: |-
    This command Remove a Proxy Application.
  summary: ""
- title: 'Example 2: Remove a Proxy Application, and remove it from Microsoft Entra ID completely'
  code: |-
    PS C:\> Remove-EntraBetaApplicationProxyApplication -ObjectId 0d7b0f02-3f63-414d-8d20-4b8bd0291e42 -RemoveADApplication $true
  description: |-
    This command Remove a Proxy Application, and remove it from Microsoft Entra ID completely.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique application ID of the application.
    This ObjectId can be found using the Get-EntraBetaApplication command.
    You can also find this ObjectId in the Microsoft by navigating to Microsoft Entra ID > App registrations > All applications. Select your application. This will takes you to the application's overview page. Use the ObjectId on that page.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: RemoveADApplication
  description: |+
    This RemoveADApplication parameter allows you to delete application completely.
    When this RemoveADApplication is false (default), Application Proxy properties are removed from the application, but the application still exists.
    If this RemoveADApplication is true, the application is removed from Microsoft Entra ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Remove-EntraBetaApplicationProxyApplication
name: Remove-EntraBetaApplicationProxyApplication
description: |-
  The Remove-EntraBetaApplicationProxyApplication cmdlet removes Application Proxy configurations from a specific application in Microsoft Entra ID, and can delete the application completely if specified.
metadata:
  title: Remove-EntraBetaApplicationProxyApplication
  description: This article provides details on the Remove-EntraBetaApplicationProxyApplication command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 04/16/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
