### YamlMime:PowershellCmdlet
summary: |-
  Delete an application by ObjectId.
module: Microsoft.Graph.Entra.Beta
notes: ""
links:
- text: Get-EntraBetaApplication
  href: Get-EntraBetaApplication.yml
- text: New-EntraBetaApplication
  href: New-EntraBetaApplication.yml
- text: Set-EntraBetaApplication
  href: Set-EntraBetaApplication.yml
syntaxes:
- >-
  Remove-EntraBetaApplication 
      -ObjectId <String>
   [<CommonParameters>]
examples:
- title: 'Example 1: Remove an application'
  code: |-
    PS C:\>Remove-EntraBetaApplication -ObjectId "acd10942-5747-4385-8824-4c5d5fa904f9"
  description: |-
    This command removes the specified application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of an application in Microsoft Entra ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Remove-EntraBetaApplication
name: Remove-EntraBetaApplication
description: |-
  The **Remove-EntraBetaApplication** cmdlet removes the specified application from Microsoft Entra ID.
metadata:
  title: Remove-EntraBetaApplication
  description: This article provides details on the Remove-EntraBetaApplication command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/05/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
