### YamlMime:PowershellCmdlet
summary: |-
  Permanently delete a recently deleted application object from deleted items.
module: Microsoft.Graph.Entra.Beta
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Remove-EntraBetaDeletedApplication 
   [-ObjectId] <String> 
  [<CommonParameters>]
examples:
- title: 'Example 1: Remove deleted application object'
  code: |-
    PS C:\> $Id = Get-EntraBetaDeletedApplication -SearchString "newtest10" 
    PS C:\> Remove-EntraBetaDeletedApplication -ObjectId $Id.id
  description: |-
    This command removes recently deleted application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique identifier of deleted application.
  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Remove-EntraBetaDeletedApplication
name: Remove-EntraBetaDeletedApplication
description: |-
  Permanently delete a recently deleted application object from deleted items. After an item is permanently deleted, it can't be restored.
metadata:
  title: Remove-EntraBetaDeletedApplication
  description: This article provides details on the Remove-EntraBetaDeletedApplication command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 04/17/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
