### YamlMime:PowershellCmdlet
summary: |-
  Removes a password credential from an application.
module: Microsoft.Graph.Entra.Beta
notes: ""
syntaxes:
- >-
  Remove-EntraBetaApplicationPasswordCredential -ObjectId <String> -KeyId <String>
   [<CommonParameters>]
examples:
- title: 'Example 1: Remove an application password credential'
  code: |-
    PS C:\> $AppID = (Get-EntraBetaApplication -Top 1).ObjectId
    PS C:\> $KeyIDs = Get-EntraBetaApplicationPasswordCredential -ObjectId $AppId
    PS C:\> Remove-EntraBetaApplicationPasswordCredential -ObjectId $AppId -KeyId $KeyIds[0].KeyId
  description: |-
    The first command gets the ID of an application by using the Get-EntraBetaApplication (./Get-EntraBetaApplication.md)cmdlet, and then stores it in the $AppID variable.

    The second command gets the password credential for the application identified by $AppID by using the Get-EntraBetaApplicationPasswordCredential (./ Get-EntraBetaApplicationPasswordCredential.md)cmdlet. 
    The command stores it in the $KeyId variable.

    The final command removes the application password credential for the application identified by $AppID.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: KeyId
  isRequired: true
  description: |+
    @{Text=}

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of the application in Azure AD.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Remove-EntraBetaApplicationPasswordCredential
name: Remove-EntraBetaApplicationPasswordCredential
description: |-
  The Remove-EntraBetaApplicationPasswordCredential cmdlet removes a password credential from an application in Azure Active Directory (AD).
metadata:
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
