### YamlMime:PowershellCmdlet
summary: |-
  Removes the verified publisher from an application.
module: Microsoft.Graph.Entra.Beta
notes: ""
inputs:
- name: <xref href="string" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Remove-EntraBetaMSApplicationVerifiedPublisher -AppObjectId <String> [<CommonParameters>]
examples:
- title: 'Example 1: Remove the verified publisher from an application.'
  code: |-
    $appObjId = 'ad6c71a5-e48f-4320-bb59-92642a2d8d9f'
              Remove-EntraBetaMSApplicationVerifiedPublisher -AppObjectId $appObjId
  description: ""
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AppObjectId
  isRequired: true
  description: |+
    The unique identifier of an Azure Active Directory Application object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Remove-EntraBetaMSApplicationVerifiedPublisher
name: Remove-EntraBetaMSApplicationVerifiedPublisher
description: |-
  Removes the verified publisher from an application.
metadata:
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
