### YamlMime:PowershellCmdlet
summary: |-
  The Remove-EntraBetaApplicationProxyConnectorGroup cmdlet deletes an Application Proxy Connector group.
module: Microsoft.Graph.Entra.Beta.Remove-EntraBetaApplicationProxyConnectorGroup
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Remove-EntraBetaApplicationProxyConnectorGroup 
   -Id <String> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Remove a specific Connector Group'
  code: |-
    PS C:\> Get-EntraBetaApplicationProxyConnectorGroup -Id 59462d3c-a1bc-40a0-9bed-be799357ebce
  description: |-
    This command Remove a specific Connector Group.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    The ID of the Connector group to delete.
    You can find this value by running the Get-EntraBetaApplicationProxyConnectorGroup command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Remove-EntraBetaApplicationProxyConnectorGroup.
name: Remove-EntraBetaApplicationProxyConnectorGroup.
description: |-
  The Remove-EntraBetaApplicationProxyConnectorGroup cmdlet deletes an Application Proxy Connector Group.
  It can only be used on an empty connector group, with no connectors assigned.
metadata:
  title: Remove-EntraBetaApplicationProxyConnectorGroup.
  description: This article provides details on the Remove-EntraBetaApplicationProxyConnectorGroup command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 04/03/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
