### YamlMime:PowershellCmdlet
summary: |-
  Remove a password from an application.
module: Microsoft.Graph.Entra.Beta
notes: ""
inputs:
- name: <xref href="string" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Remove-EntraBetaMSApplicationPassword -ObjectId <String> [-KeyId <String>] [<CommonParameters>]
examples:
- title: 'Example 1: Removes a password from an application'
  code: |-
    PS C:\>Remove-EntraBetaMSApplicationPassWord -ObjectId 1f88e99f-37a3-468f-80ae-e07b62ed0287 -KeyId 80e561ed-44ed-48dc-8c09-9d4803e26e4c
  description: |-
    This command remove the specified password from the specified application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: KeyId
  description: |+
    The unique identifier for the key.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique identifier of the object specific Azure Active Directory object

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Remove-EntraBetaMSApplicationPassword
name: Remove-EntraBetaMSApplicationPassword
description: |-
  Remove a password from an application.
metadata:
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
