### YamlMime:PowershellCmdlet
summary: |-
  The Remove-EntraBetaApplicationProxyApplicationConnectorGroupcmdlet sets the connector group assigned for the specified application to 'Default' and removes the current assignment.
module: Microsoft.Graph.Entra.Beta
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Remove-EntraBetaApplicationProxyApplicationConnectorGroup
   -ObjectId <String> 
   [<CommonParameters>]
examples:
- title: "Example 1: Remove the Connector Group associated with an application, setting the group to 'Default'"
  code: |-
    PS C:\> Remove-EntraBetaApplicationProxyApplicationConnectorGroup -ObjectId 59462d3c-a1bc-40a0-9bed-be799357ebce
  description: |-
    This command Remove the Connector Group associated with an application, setting the group to 'Default.'
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique application ID of the application.
    The application ID can be found using the Get-EntraBetaApplication command.
    You can also find objectId  in the Microsoft Entra Admin Center by navigating to Microsoft Entra ID > App registrations > All applications. Select your application. From the application overview page, copy the ObjectId.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Remove-EntraBetaApplicationProxyApplicationConnectorGroup
name: Remove-EntraBetaApplicationProxyApplicationConnectorGroup
description: |-
  If your application is already in the 'Default' group, you see an error because the application can't be removed from the 'Default' group unless it's being added to another group.
  The application must be configured for Application Proxy in Microsoft Entra ID.
metadata:
  title: Remove-EntraBetaApplicationProxyApplicationConnectorGroup
  description: This article provides details on the Remove-EntraBetaApplicationProxyApplicationConnectorGroup command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 04/03/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
