### YamlMime:PowershellCmdlet
summary: |-
  Updates settings for a federated domain.
module: Microsoft.Graph.Entra.Beta
notes: ""
syntaxes:
- >-
  Set-EntraBetaDomainFederationSettings [-DomainName] <String> [[-SigningCertificate] <String>]
   [[-NextSigningCertificate] <String>] [[-LogOffUri] <String>] [[-PassiveLogOnUri] <String>]
   [[-ActiveLogOnUri] <String>] [[-IssuerUri] <String>] [[-FederationBrandName] <String>]
   [[-MetadataExchangeUri] <String>] [[-PreferredAuthenticationProtocol] <String>]
   [[-SigningCertificateUpdateStatus] <Object>] [[-PromptLoginBehavior] <String>] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> {{ Add example code here }}
  description: |-
    {{ Add example description here }}
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ActiveLogOnUri
  description: |+
    A URL that specifies the end point used by active clients when authenticating with domains set up for single sign-on (also known as identity federation) in
    Microsoft Azure Active Directory.

  defaultValue: None
  pipelineInput: true
  position: "6"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DomainName
  isRequired: true
  description: |+
    The fully qualified domain name (FQDN) to update.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FederationBrandName
  description: |+
    The name of the string value shown to users when signing in to Microsoft Azure Active Directory.
    We recommend that customers use something that is familiar to
    users such as "Contoso Inc."

  defaultValue: None
  pipelineInput: true
  position: "8"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: IssuerUri
  description: |+
    The unique identifier of the domain in the Microsoft Azure Active Directory Identity platform derived from the federation server.

  defaultValue: None
  pipelineInput: true
  position: "7"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: LogOffUri
  description: |+
    The URL clients are redirected to when they sign out of Microsoft Azure Active Directory services.

  defaultValue: None
  pipelineInput: true
  position: "4"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: MetadataExchangeUri
  description: |+
    The URL that specifies the metadata exchange end point used for authentication from rich client applications such as Lync Online.

  defaultValue: None
  pipelineInput: true
  position: "9"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: NextSigningCertificate
  description: |+
    The next token signing certificate that will be used to sign tokens when the primary signing certificate expires.

  defaultValue: None
  pipelineInput: true
  position: "3"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PassiveLogOnUri
  description: |+
    The URL that web-based clients will be directed to when signing in to Microsoft Azure Active Directory services.

  defaultValue: None
  pipelineInput: true
  position: "5"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PreferredAuthenticationProtocol
  description: |+
    Specifies the preferred authentication protocol.

  defaultValue: None
  pipelineInput: true
  position: "10"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PromptLoginBehavior
  description: |+
    Specifies the prompt login behavior.

  defaultValue: None
  pipelineInput: true
  position: "12"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SigningCertificate
  description: |+
    The current certificate used to sign tokens passed to the Microsoft Azure Active Directory Identity platform.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Object" data-throw-if-not-resolved="False" />
  name: SigningCertificateUpdateStatus
  description: |+
    Specifies the update status of the signing certificate.

  defaultValue: None
  pipelineInput: true
  position: "11"
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Set-EntraBetaDomainFederationSettings
name: Set-EntraBetaDomainFederationSettings
description: |-
  The Set-EntraBetaDomainFederationSettings cmdlet is used to update the settings of a single sign-on domain.
metadata:
  external help file: Microsoft.Graph.Entra.Beta-help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
