### YamlMime:PowershellCmdlet
summary: |-
  The Set-EntraBetaApplicationProxyApplicationConnectorGroup cmdlet assigns the given connector group to a specified application.
module: Microsoft.Graph.Entra.Beta.Set-EntraBetaApplicationProxyApplicationConnectorGroup
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Set-EntraBetaApplicationProxyApplicationConnectorGroup 
   -ObjectId <String> 
   -ConnectorGroupId <String>
   [<CommonParameters>]
examples:
- title: 'Example 1: Set a new Connector Group for a specific application'
  code: |-
    PS C:\> Set-EntraBetaApplicationProxyApplicationConnectorGroup -ObjectId 59462d3c-a1bc-40a0-9bed-be799357ebce -ConnectorGroupId a39b9095-8dc8-4d3a-86c3-e7b5c3f0fb84
  description: |-
    This command Set a new Connector Group for a specific application
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ConnectorGroupId
  isRequired: true
  description: |+
    The ID of the Connector group that should be assigned to the application.
    You can find the Connector Group ID by using the Get-EntraBetaApplicationProxyConnectorGroup command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique application ID for the application the Connector group assigns to.
    The application ID can be found using the Get-EntraBetaApplication command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Set-EntraBetaApplicationProxyApplicationConnectorGroup.
name: Set-EntraBetaApplicationProxyApplicationConnectorGroup.
description: |-
  The Set-EntraBetaApplicationProxyApplicationConnectorGroup cmdlet sets the connector group assigned for the specified application.
  The application must be configured for Application Proxy in Microsoft Entra ID.
metadata:
  title: Set-EntraBetaApplicationProxyApplicationConnectorGroup.
  description: This article provides details on the Set-EntraBetaApplicationProxyApplicationConnectorGroup command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 04/03/2023
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
