### YamlMime:PowershellCmdlet
summary: |-
  The Set-EntraBetaApplicationProxyConnector cmdlet allows reassignment of the connector to another connector group.
module: Microsoft.Graph.Entra.Beta.Set-EntraBetaApplicationProxyConnector
notes: ""
links:
- text: Get-EntraBetaApplicationProxyConnectorGroup
  href: Get-EntraBetaApplicationProxyConnectorGroup.yml
- text: Get-EntraBetaApplicationProxyConnector
  href: Get-EntraBetaApplicationProxyConnector.yml
syntaxes:
- >-
  Set-EntraBetaApplicationProxyConnector 
   -Id <String> 
   -ConnectorGroupId <String> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Move a Connector to a different Connector Group'
  code: |-
    PS C:\> Set-EntraBetaApplicationProxyConnector -Id 834c5dd6-f2e8-47ae-973a-9fc769289b3d -ConnectorGroupId a39b9095-8dc8-4d3a-86c3-e7b5c3f0fb84
  description: |-
    This example demonstrates how to move a Connector to a different Connector Group.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ConnectorGroupId
  isRequired: true
  description: |+
    The unique identifer of the target application proxy connector group in Microsoft Entra ID.
    You can find this value using the Get-EntraBetaApplicationProxyConnectorGroup command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    The ID of the Connector being moved.
    You can find this value using the Get-EntraBetaApplicationProxyConnector command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Set-EntraBetaApplicationProxyConnector.
name: Set-EntraBetaApplicationProxyConnector.
description: |-
  The Set-EntraBetaApplicationProxyConnector cmdlet allows reassignment of the connector to another connector group.
metadata:
  title: Set-EntraBetaApplicationProxyConnector.
  description: This article provides details on the Set-EntraBetaApplicationProxyConnector command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 04/02/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
