### YamlMime:PowershellCmdlet
summary: |-
  The Set-EntraBetaApplicationProxyConnectorGroup cmdlet allows you to change the name of a given Application Proxy connector group.
module: Microsoft.Graph.Entra.Beta.Set-EntraBetaApplicationProxyConnectorGroup
notes: ""
syntaxes:
- >-
  Set-EntraBetaApplicationProxyConnectorGroup 
   -Id <String> 
   -Name <Name> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Rename a Connector Group to "Offsite Application Servers"'
  code: |-
    PS C:\> Set-EntraBetaApplicationProxyConnectorGroup -Id d533d7b1-fd92-49e8-a200-3e7dcf7c2ab5 -Name "Offsite Application Servers"
  description: |-
    This command Rename a Connector Group to "Offsite Application Servers"
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    The unique identifier of the Connector group that should be renamed.
    You can find the ID using the Get-EntraBetaApplicationProxyConnectorGroup command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Name" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    The new name for the Connector group.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Set-EntraBetaApplicationProxyConnectorGroup.
name: Set-EntraBetaApplicationProxyConnectorGroup.
description: |-
  The Set-EntraBetaApplicationProxyConnectorGroup cmdlet allows you to change the name of a given Application Proxy connector group.
metadata:
  title: Set-EntraBetaApplicationProxyConnectorGroup.
  description: This article provides details on the Set-EntraBetaApplicationProxyConnectorGroup command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 04/15/2023
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
