### YamlMime:PowershellCmdlet
summary: |-
  The Set-EntraBetaApplicationProxyApplicationSingleSignOn cmdlet allows you to set and modify single sign-on (SSO) settings for an application configured for Application Proxy in Microsoft Entra ID.
module: Microsoft.Graph.Entra.Beta
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    System.Nullable\`1\[\[Microsoft.Open.MSGraph.Model.OnPremisesPublishingSingleSignOnObject+SingleSignOnModeEnum, Microsoft.Open.MS.GraphV10.Client, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null\]\] System.Nullable\`1\[\[Microsoft.Open.MSGraph.Model.OnPremisesPublishingKerberosSignOnSettingsObject+KerberosSignOnMappingAttributeTypeEnum, Microsoft.Open.MS.GraphV10.Client, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null\]\]
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Set-EntraBetaApplicationProxyApplicationSingleSignOn 
   -ObjectId <String> 
   -SingleSignOnMode <SingleSignOnModeEnum>
   [-KerberosInternalApplicationServicePrincipalName <String>]
   [-KerberosDelegatedLoginIdentity <KerberosSignOnMappingAttributeTypeEnum>] 
   [<CommonParameters>]
examples:
- title: 'Example 1:  Assign an application to use Kerberos Constrained Delegation, and specify required parameters.'
  code: |-
    PS C:\> Set-EntraBetaApplicationProxyApplicationSingleSignOn -ObjectId 4eba5342-8d17-4eac-a1f6-62a0de26311e -SingleSignOnMode OnPremisesKerberos -KerberosInternalApplicationServicePrincipalName "https/www.adventure-works.com" -KerberosDelegatedLoginIdentity OnPremisesUserPrincipalName
  description: |-
    This command Assign an application to use Kerberos Constrained Delegation, and specify required parameters.
  summary: ""
- title: 'Example 2: Remove SSO from an application'
  code: |-
    PS C:\> Set-EntraBetaApplicationProxyApplicationSingleSignOn -ObjectId 4eba5342-8d17-4eac-a1f6-62a0de26311e -SingleSignOnMode None
  description: |-
    This example demonstrates how to Remove SSO from an application.
  summary: ""
parameters:
- type: <xref href="KerberosSignOnMappingAttributeTypeEnum" data-throw-if-not-resolved="False" />
  name: KerberosDelegatedLoginIdentity
  description: |+
    The identity that the Connector can use on behalf of your users to authenticate.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: UserPrincipalName, OnPremisesUserPrincipalName, UserPrincipalUsername, OnPremisesUserPrincipalUsername, OnPremisesSAMAccountName
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: KerberosInternalApplicationServicePrincipalName
  description: |+
    The internal application SPN of the application server.
    This SPN needs to be in the list of services to which the Connector can present delegated credentials.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique application ID of the application that needs different SSO settings.
    ObjectId can be found using the Get-EntraBetaApplication command.
    You can also find this in the Microsoft Portal by navigating to Microsoft Entra ID, Enterprise Applications, All Applications, Select your application, go to the properties tab, and use the ObjectId on that page.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SingleSignOnModeEnum" data-throw-if-not-resolved="False" />
  name: SingleSignOnMode
  isRequired: true
  description: |+
    Choose the type of SSO you would like the application to use.
    Only three SSO settings are supported in PowerShell, for more options, please use the Microsoft Portal.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: None, OnPremisesKerberos, HeaderBased
uid: Microsoft.Graph.Entra.Beta.Set-EntraBetaApplicationProxyApplicationSingleSignOn
name: Set-EntraBetaApplicationProxyApplicationSingleSignOn
description: |-
  The Set-EntraBetaApplicationProxyApplicationSingleSignOn cmdlet allows you to set and modify single sign-on (SSO) settings for an application configured for Application Proxy in Microsoft Entra ID.
  This is limited to setting No SSO, Kerberos Constrained Delegation (for applications using Integrated Windows Authentication), and Header-based SSO.
metadata:
  title: Set-EntraBetaApplicationProxyApplicationSingleSignOn
  description: This article provides details on the Set-EntraBetaApplicationProxyApplicationSingleSignOn command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 04/03/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
