### YamlMime:PowershellCmdlet
summary: |-
  {{ Fill in the Synopsis }}
module: Microsoft.Graph.Entra.Beta
notes: ""
inputs:
- name: <xref href="System.UInt32" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.Guid" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Set-EntraBetaDirSyncConfiguration -AccidentalDeletionThreshold <UInt32> [-Force] [<CommonParameters>]
- Set-EntraBetaDirSyncConfiguration [-TenantId <Guid>] [-Force] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> {{ Add example code here }}
  description: |-
    {{ Add example description here }}
  summary: ""
parameters:
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: AccidentalDeletionThreshold
  isRequired: true
  description: |+
    {{ Fill AccidentalDeletionThreshold Description }}

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    {{ Fill Force Description }}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: TenantId
  description: |+
    {{ Fill TenantId Description }}

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Set-EntraBetaDirSyncConfiguration
name: Set-EntraBetaDirSyncConfiguration
description: |-
  {{ Fill in the Description }}
metadata:
  external help file: Microsoft.Graph.Entra.Beta-help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
