### YamlMime:PowershellCmdlet
summary: |-
  Sets the logo for an application object.
module: Microsoft.Graph.Entra.Beta
notes: ""
inputs:
- name: <xref href="String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Byte" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
syntaxes:
- >-
  Set-EntraBetaMSApplicationLogo 
   -ObjectId <String> 
   -Content <Byte[]> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Sets the logo of the application'
  code: |-
    PS C:\>Set-EntraBetaMSApplicationLogo -ObjectId 121ce3aa-64cb-44f2-99e8-deb705caeddd -Content {imagebytearray}
  description: |-
    This command updates the application logo.
  summary: ""
parameters:
- type: <xref href="Byte" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Content
  isRequired: true
  description: |+
    An ImageByteArray that is to be used as the application logo

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique identifier of the object specific Microsoft Entra ID object

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Set-EntraBetaMSApplicationLogo
name: Set-EntraBetaMSApplicationLogo
description: |-
  Sets the logo for an application object.
metadata:
  title: Set-EntraBetaMSApplicationLogo
  description: This article provides details on the Set-EntraBetaMSApplicationLogo command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 04/22/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
