### YamlMime:PowershellCmdlet
summary: |-
  The Set-EntraBetaApplicationProxyApplication allows you to modify and set configurations for an application in Microsoft Entra ID configured to use ApplicationProxy.
module: Microsoft.Graph.Entra.Beta
notes: ""
syntaxes:
- >-
  Set-EntraBetaApplicationProxyApplication 
   -ObjectId <String> 
   [-ExternalUrl <String>] 
   [-InternalUrl <String>]
   [-ExternalAuthenticationType <ExternalAuthenticationTypeEnum>] 
   [-IsTranslateHostHeaderEnabled <Boolean>]
   [-IsHttpOnlyCookieEnabled <Boolean>] 
   [-IsSecureCookieEnabled <Boolean>] 
   [-IsPersistentCookieEnabled <Boolean>]
   [-IsTranslateLinksInBodyEnabled <Boolean>] 
   [-ApplicationServerTimeout <ApplicationServerTimeoutEnum>]
   [-ConnectorGroupId <String>] 
   [<CommonParameters>]
examples:
- title: 'Example 1: Update ExternalUrl, InternalUrl, ExternalAuthenticationType, and IsTranslateHostHeaderEnabled parameter.'
  code: |-
    PS C:\> Set-EntraBetaApplicationProxyApplication -ObjectId 61ec5727-7d0b-40b3-bd4e-817076b540fa -ExternalUrl "https://testp-m365x99297270.msappproxy.net/" -InternalUrl "https://testp.com/" -ExternalAuthenticationType AadPreAuthentication -IsTranslateHostHeaderEnabled $false

    ObjectId                                 : 61ec5727-7d0b-40b3-bd4e-817076b540fa
    externalAuthenticationType               : aadPreAuthentication
    applicationServerTimeout                 : Long
    externalUrl                              : https://testp-m365x99297270.msappproxy.net/
    internalUrl                              : https://testp.com/
    isTranslateHostHeaderEnabled             : False
    isTranslateLinksInBodyEnabled            : False
    isOnPremPublishingEnabled                : True
    verifiedCustomDomainCertificatesMetadata :
    verifiedCustomDomainKeyCredential        :
    verifiedCustomDomainPasswordCredential   :
    singleSignOnSettings                     : @{singleSignOnMode=none; kerberosSignOnSettings=}
    isHttpOnlyCookieEnabled                  : False
    isSecureCookieEnabled                    : False
    isPersistentCookieEnabled                : False
  description: |-
    This command Update ExternalUrl, InternalUrl, ExternalAuthenticationType, and IsTranslateHostHeaderEnabled parameter.
  summary: ""
- title: 'Example 2: Update IsHttpOnlyCookieEnabled, IsSecureCookieEnabled, and IsPersistentCookieEnabled  parameter.'
  code: |-
    PS C:\> Set-EntraBetaApplicationProxyApplication -ObjectId 61ec5727-7d0b-40b3-bd4e-817076b540fa -ExternalUrl "https://testp-m365x99297270.msappproxy.net/" -InternalUrl "https://testp.com/" -IsHttpOnlyCookieEnabled $false -IsSecureCookieEnabled $false -IsPersistentCookieEnabled $false

    ObjectId                                 : 61ec5727-7d0b-40b3-bd4e-817076b540fa
    externalAuthenticationType               : aadPreAuthentication
    applicationServerTimeout                 : Long
    externalUrl                              : https://testp-m365x99297270.msappproxy.net/
    internalUrl                              : https://testp.com/
    isTranslateHostHeaderEnabled             : False
    isTranslateLinksInBodyEnabled            : False
    isOnPremPublishingEnabled                : True
    verifiedCustomDomainCertificatesMetadata :
    verifiedCustomDomainKeyCredential        :
    verifiedCustomDomainPasswordCredential   :
    singleSignOnSettings                     : @{singleSignOnMode=none; kerberosSignOnSettings=}
    isHttpOnlyCookieEnabled                  : False
    isSecureCookieEnabled                    : False
    isPersistentCookieEnabled                : False
  description: |-
    This command Update IsHttpOnlyCookieEnabled, IsSecureCookieEnabled, and IsPersistentCookieEnabled  parameter.
  summary: ""
- title: 'Example 3: Update IsTranslateLinksInBodyEnabled, ApplicationServerTimeout, and  ConnectorGroupId parameter.'
  code: |-
    PS C:\> Set-EntraBetaApplicationProxyApplication -ObjectId 61ec5727-7d0b-40b3-bd4e-817076b540fa -ExternalUrl "https://testp-m365x99297270.msappproxy.net/" -InternalUrl "https://testp.com/" -IsTranslateLinksInBodyEnabled $false -ApplicationServerTimeout Long  -ConnectorGroupId 55311d30-74d7-4cad-a7d7-f8d76e110345

    ObjectId                                 : 61ec5727-7d0b-40b3-bd4e-817076b540fa
    externalAuthenticationType               : aadPreAuthentication
    applicationServerTimeout                 : Long
    externalUrl                              : https://testp-m365x99297270.msappproxy.net/
    internalUrl                              : https://testp.com/
    isTranslateHostHeaderEnabled             : False
    isTranslateLinksInBodyEnabled            : False
    isOnPremPublishingEnabled                : True
    verifiedCustomDomainCertificatesMetadata :
    verifiedCustomDomainKeyCredential        :
    verifiedCustomDomainPasswordCredential   :
    singleSignOnSettings                     : @{singleSignOnMode=none; kerberosSignOnSettings=}
    isHttpOnlyCookieEnabled                  : False
    isSecureCookieEnabled                    : False
    isPersistentCookieEnabled                : False
  description: |-
    This command Update IsTranslateLinksInBodyEnabled, ApplicationServerTimeout, and  ConnectorGroupId parameter.
  summary: ""
parameters:
- type: <xref href="ApplicationServerTimeoutEnum" data-throw-if-not-resolved="False" />
  name: ApplicationServerTimeout
  description: |+
    Specifies the backend server timeout type.
    Set this value to Long only if your application is slow to authenticate and connect.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ConnectorGroupId
  description: |+
    Provide the ID of the Connector group you would like assigned to this application.
    You can find this value by using the Get-EntraBetaApplicationProxyConnectorGroup command.
    Connectors process the remote access to your application, and connector groups help you organize connectors and apps by region, network, or purpose.
    If you don't have any connector groups created yet, your app is assigned to Default.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ExternalAuthenticationTypeEnum" data-throw-if-not-resolved="False" />
  name: ExternalAuthenticationType
  description: |+
    How Application Proxy verifies users before giving them access to your application. 
    AadPreAuth: Application Proxy redirects users to sign in with Microsoft Entra ID, which authenticates their permissions for the directory and application.
    We recommend keeping this option as the default, so that you can take advantage of Microsoft Entra ID security features like conditional access and multifactor authentication.
    Pass through: Users don't have to authenticate against Microsoft Entra ID to access the application.
    You can still set up authentication requirements on the backend.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ExternalUrl
  description: |+
    The address your users go to in order to access the app from outside your network.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: InternalUrl
  description: |+
    The URL that you use to access the application from inside your private network.
    You can provide a specific path on the backend server to publish, while the rest of the server is unpublished.
    In this way, you can publish different sites on the same server as different apps, and give each one its own name and access rules.
    If you publish a path, make sure that it includes all the necessary images, scripts, and style sheets for your application.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsHttpOnlyCookieEnabled
  description: |+
    Allows application proxy to include the HTTPOnly flag in HTTP response headers. This flag provides extra security benefits, for example, it prevents client-side scripting (CSS) from copying or modifying the cookies.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsPersistentCookieEnabled
  description: |+
    Allows application proxy to set its access cookies to not expire when the web browser is closed. The persistence lasts until the access token expires, or until the user manually deletes the persistent cookies.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsSecureCookieEnabled
  description: |+
    Allows application proxy to include the Secure flag in HTTP response headers. Secure Cookies enhances security by transmitting cookies over a "TLS" secured channel such as HTTPS. TLS prevents cookie transmission in clear text.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsTranslateHostHeaderEnabled
  description: |+
    If set to true, translates urls in headers.
    Keep this value true unless your application required the original host header in the authentication request.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsTranslateLinksInBodyEnabled
  description: |+
    If set to true, translates urls in body.
    Keep this value as No unless you have to hardcoded HTML links to other on-premises applications, and don't use custom domains.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies a unique application ID of an application in Microsoft Entra ID.
    This objectid can be found using the Get-EntraBetaApplication command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Set-EntraBetaApplicationProxyApplication
name: Set-EntraBetaApplicationProxyApplication
description: |-
  The Set-EntraBetaApplicationProxyApplication allows you to modify and set other settings for an application in Microsoft Entra ID configured to use ApplicationProxy.
metadata:
  title: Set-EntraBetaApplicationProxyApplication
  description: This article provides details on the Set-EntraBetaApplicationProxyApplication command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 04/15/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
