### YamlMime:PowershellCmdlet
summary: |-
  Sets the logo for an Application
module: Microsoft.Graph.Entra.Beta
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    System.IO.Stream System.Byte\[\]
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Set-EntraBetaApplicationLogo 
   [-ObjectId <String>] 
   -FilePath <String> 
   [<CommonParameters>]
- >-
  Set-EntraBetaApplicationLogo 
   [-ObjectId <String>] 
   [<CommonParameters>]
- >-
  Set-EntraBetaApplicationLogo 
   [-ObjectId <String>]  
   [<CommonParameters>]
examples:
- title: 'Example 1: Sets the application logo for the application specified by the ObjectID parameter'
  code: |-
    PS C:\WINDOWS\system32> Set-EntraBetaApplicationLogo -ObjectId 79592454-dea7-4660-9d91-f1768e5055ac -FilePath D:\applogo.jpg
  description: |-
    This cmdlet sets the application logo for the application specified by the ObjectID parameter to the image specified with the Filepath parameter.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FilePath
  isRequired: true
  description: |+
    The file path of the file that is to be uploaded as the application logo

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  description: |+
    The ObjectID of the Application for which the logo is set.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Beta.Set-EntraBetaApplicationLogo
name: Set-EntraBetaApplicationLogo
description: |-
  This cmdlet is used to set the logo for an application.
metadata:
  title: Set-EntraBetaApplicationLogo
  description: This article provides details on the Set-EntraBetaApplicationLogo command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 04/22/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra.Beta-Help.xml
  Module Name: Microsoft.Graph.Entra.Beta
  online version: ""
  PlatyPS schema version: 2.0.0
