### YamlMime:PowershellCmdlet
summary: |-
  Adds Microsoft Entra environment to the settings file.
module: Microsoft.Graph.Entra
notes: ""
links:
- text: Get-EntraEnvironment
  href: Get-EntraEnvironment.yml
syntaxes:
- >-
  Add-EntraEnvironment 
     [-Name] <String>
     [-AzureADEndpoint] <String>
     [-GraphEndpoint] <String>
     [-ProgressAction <ActionPreference>]
     [-WhatIf]
     [-Confirm]
     [<CommonParameters>]
examples:
- title: 'Example 1: Add a user defined environment'
  code: |-
    PS C:\>Add-EntraEnvironment -Name "Canary" -GraphEndpoint "https://canary.graph.microsoft.com" -AzureADEndpoint "https://login.microsoftonline.com"
    Name     AzureADEndpoint                      GraphEndpoint                 Type
    ----     ---------------                      -------------                 ----
    Canary    https://login.microsoftonline.com   https://microsoftgraph.com User-defined                                                                                    {}
  description: |-
    Adds a User defined Entra environment to the settings file.
  summary: ""
parameters:
- type: <span>undefined</span>
  name: AzueADEndpoint
  isRequired: true
  description: |+
    Specifies the AzureADEndpoint URL of an environment

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <span>undefined</span>
  name: GraphEndpoint
  isRequired: true
  description: |+
    Specifies the GraphEndpoint URL of an environment

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <span>undefined</span>
  name: Name
  isRequired: true
  description: |+
    Specifies the name of an environment

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Add-EntraEnvironment
name: Add-EntraEnvironment
description: |-
  Adds Microsoft Entra environment to the settings file.
metadata:
  title: Add-EntraEnvironment
  description: This article provides details on the Add-EntraEnvironment command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/16/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
