### YamlMime:PowershellCmdlet
summary: |-
  Adds an owner for an application object.
module: Microsoft.Graph.Entra
notes: ""
inputs:
- name: <xref href="String" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-EntraMSApplicationOwner
  href: Get-EntraMSApplicationOwner.yml
- text: Remove-EntraMSApplicationOwner
  href: Remove-EntraMSApplicationOwner.yml
syntaxes:
- >-
  Add-EntraMSApplicationOwner 
   -ObjectId <String> 
   -RefObjectId <String> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Add an owner to an application'
  code: |-
    PS C:\> $ApplicationId = (Get-EntraMSApplication -Top 1).ObjectId
    PS C:\> $UserObjectId = (Get-EntraMSUser -Top 1).ObjectId
    PS C:\> Add-EntraMSApplicationOwner -ObjectId $ApplicationId -RefObjectId $UserObjectId
  description: |-
    The first command gets an application using [Get-EntraMSApplication](./Get-EntraMSApplication.yml) cmdlet, and stores 
    the ObjectId property value in $ApplicationId variable.  

    The second command gets a user using [Get-EntraMSUser](./Get-EntraMSUser.md) cmdlet, and stores 
    the ObjectId property value in $UserObjectId variable.  

    This final command adds an owner in $UserObjectId to an application in $ApplicationId.

    This command adds an owner to an application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique identifier of the object specific Microsoft Entra ID object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: RefObjectId
  isRequired: true
  description: |+
    The unique identifier of the specific Microsoft Entra ID object that is assigned as owner/manager/member.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Add-EntraMSApplicationOwner
name: Add-EntraMSApplicationOwner
description: |-
  Adds an owner for an application object.
metadata:
  title: Add-EntraMSApplicationOwner
  description: This article provides details on the Add-EntraMSApplicationOwner command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/06/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
