### YamlMime:PowershellCmdlet
summary: |-
  The Get-EntraApplicationProxyApplicationConnectorGroup cmdlet retrieves the connector group assigned for a specific application.
module: Microsoft.Graph.Entra.Get-EntraApplicationProxyApplicationConnectorGroup
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-EntraApplicationProxyApplicationConnectorGroup 
   -ObjectId <String> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Retrieve application connector group by ID'
  code: |-
    PS C:\WINDOWS\system32> Get-EntraApplicationProxyApplicationConnectorGroup -ObjectId "8d6c6684-6f8c-42e2-8914-32ed2adf9ccf"
  description: |-
    This example demonstrates how to retrieve specific application connector group by providing ID.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    ObjectId is the ID of the application.
    This can be found using the [Get-EntraApplication](Get-EntraApplication.yml) command.
    You can also find this in the Microsoft Portal by navigating to Microsoft Entra ID, Enterprise Applications, All Applications, Select your application, go to the properties tab, and use the ObjectId on that page.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Get-EntraApplicationProxyApplicationConnectorGroup.
name: Get-EntraApplicationProxyApplicationConnectorGroup.
description: |-
  The Get-EntraApplicationProxyApplicationConnectorGroup cmdlet retrieves the connector group assigned for the specified application.
  The application must be configured for Application Proxy in Microsoft Entra ID.
metadata:
  title: Get-EntraApplicationProxyApplicationConnectorGroup.
  description: This article provides details on the Get-EntraApplicationProxyApplicationConnectorGroup command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/22/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
