### YamlMime:PowershellCmdlet
summary: |-
  Gets application extension properties.
module: Microsoft.Graph.Entra
notes: ""
links:
- text: New-EntraApplicationExtensionProperty
  href: New-EntraApplicationExtensionProperty.yml
- text: Remove-EntraApplicationExtensionProperty
  href: Remove-EntraApplicationExtensionProperty.yml
syntaxes:
- >-
  Get-EntraApplicationExtensionProperty 
   -ObjectId <String>
   [<CommonParameters>]
examples:
- title: 'Example 1: Get extension properties'
  code: |-
    PS C:\>Get-EntraApplicationExtensionProperty -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84"

    ObjectId                             Name                                                    TargetObjects
    --------                             ----                                                    -------------
    344ed560-f8e7-410e-ab9f-c795a7df5c36 extension_36ee4c6c081240a2b820b22ebd02bce3_NewAttribute {}
  description: |-
    This command gets the extension properties for the specified application in Microsoft Entra ID.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the unique ID of an application in Microsoft Entra ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Get-EntraApplicationExtensionProperty
name: Get-EntraApplicationExtensionProperty
description: |-
  The Get-EntraApplicationExtensionProperty cmdlet gets application extension properties in Microsoft Entra ID.
metadata:
  title: Get-EntraApplicationExtensionProperty
  description: This article provides details on the Get-EntraApplicationExtensionProperty command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/04/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
