### YamlMime:PowershellCmdlet
summary: |-
  The Get-EntraApplicationProxyConnector cmdlet a list of all connectors, or if specified, details of a specific connector.
module: Microsoft.Graph.Entra.Get-EntraApplicationProxyConnector
notes: |-
  ## RELATED LINKS
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    System.Nullable\`1\[\[System. Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\]\] System.Nullable\`1\[\[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\]\]
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-EntraApplicationProxyConnector
   [-All] 
   [-Top <Int32>] 
   [-Filter <String>] 
   [<CommonParameters>]
- >-
  Get-EntraApplicationProxyConnector
   [-SearchString <String>] 
   [-All] 
   [<CommonParameters>]
- >-
  Get-EntraApplicationProxyConnector
   -Id <String> 
   [-All] 
   [<CommonParameters>]
examples:
- title: 'Example 1: Retrieve connectors.'
  code: |-
    PS C:\> Get-EntraApplicationProxyConnector

    Id                                   MachineName                      ExternalIp     Status
    --                                   -----------                      ----------     ------
    4c8b06e7-9751-41d5-8e5e-48e9b9bc2c66 AWCyclesApps.adventure-works.com 52.165.149.115 active
    834c5dd6-f2e8-47ae-973a-9fc769289b3d AWCyclesAD.adventure-works.com   52.165.149.131 active
  description: |-
    This example demonstrates how to retrieve all connectors.
  summary: ""
- title: 'Example 2: Retrieve connectors with ID parameter'
  code: |-
    PS C:\> Get-EntraApplicationProxyConnector -Id 4c8b06e7-9751-41d5-8e5e-48e9b9bc2c66

    Id                                   MachineName                      ExternalIp     Status
    --                                   -----------                      ----------     ------
    4c8b06e7-9751-41d5-8e5e-48e9b9bc2c66 AWCyclesApps.adventure-works.com 52.165.149.115 active
  description: |-
    This example demonstrates how to Retrieve information for a specific connector.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: All
  description: |+
    List all pages.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Specifies an oData v3.0 filter statement.
    This parameter controls which objects are returned.
    Details on querying with oData can be found here: https://www.odata.org/documentation/odata-version-3-0/odata-version-3-0-core-protocol/#queryingcollections

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    The ID of the specific connector.
    You can find ID by running the command without this parameter to get the desired ID, or by going into the portal and viewing connector details.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SearchString
  description: |+
    Specifies a search string.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Top
  description: |+
    Specifies the maximum number of records to return.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Get-EntraApplicationProxyConnector.
name: Get-EntraApplicationProxyConnector.
description: |-
  The  cmdlet retrieves the details for a given conneGet-EntraApplicationProxyConnectorctor.
  If no connectorId is specified, it retrieves all the connectors assigned to the tenant.
metadata:
  title: Get-EntraApplicationProxyConnector.
  description: This article provides details on the Get-EntraApplicationProxyConnector Command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/27/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
