### YamlMime:PowershellCmdlet
summary: |-
  Gets key settings for a federated domain.
module: Microsoft.Graph.Entra
notes: ""
outputs:
- name: <xref href="Microsoft.Online.Administration.DomainFederationSettings" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="This cmdlet returns the following settings:" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="ActiveLogOnUri" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="FederationBrandName" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="IssuerUri" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="LogOffUri" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="MetadataExchangeUri" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="NextSigningCertificate" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="PassiveLogOnUri" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="SigningCertificate" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-EntraDomainFedrationSettings 
   -DomainName <String>
   [-TenantId <Guid>]
   [<CommonParameters>]
examples:
- title: 'EXAMPLE 1: Get federation settings for specified domain'
  code: |-
    PS C:\> Get-EntraDomainFederationSettings -DomainName contoso.com
  description: |-
    This command gets federation settings for specified domain.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DomainName
  isRequired: true
  description: |+
    The fully qualified domain name to retrieve.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: TenantId
  description: |+
    The unique ID of the tenant to perform the operation on.
    If this isn't provided then the value defaults to the tenant of the current user.
    This parameter is only applicable to partner users.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Get-EntraDomainFedrationSettings
name: Get-EntraDomainFedrationSettings
description: |-
  The Get-EntraDomainFederationSettings cmdlet gets key settings from Microsoft Entra ID.
  Use the [Get-EntraFederationProperty](./Get-EntraFederationProperty.yml) cmdlet to get settings for both Microsoft Entra ID and the Entra ID Federation Services server.
metadata:
  title: Get-EntraDomainFedrationSettings
  description: This article provides details on the Get-EntraDomainFedrationSettings command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/28/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
