### YamlMime:PowershellCmdlet
summary: |-
  The Get-EntraApplicationProxyConnectorGroup cmdlet retrieves a list of all connector groups, or if specified, details of a specific connector group.
module: Microsoft.Graph.Entra
notes: |-
  ## RELATED LINKS
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    System.Nullable\`1\[\[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\]\] System.Nullable\`1\[\[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\]\]
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-EntraApplicationProxyConnectorGroup
   [-All]
   [-Top <Int32>]
   [-Filter <String>]
   [<CommonParameters>]
- >-
  Get-EntraApplicationProxyConnectorGroup
   [-SearchString <String>]
   [-All]
   [<CommonParameters>]
- >-
  Get-EntraApplicationProxyConnectorGroup
   -Id <String>
   [-All]
   [<CommonParameters>]
examples:
- title: 'Example 1: Retrieve all connector groups'
  code: |-
    PS C:\> Get-EntraApplicationProxyConnectorGroup

    Id                                   Name                ConnectorGroupType IsDefault
    --                                   ----                ------------------ ---------
    1a0bc41a-8663-4da3-934c-214640663a33 Default             applicationProxy        True
    68348ab6-4cc5-4c8c-a0f0-7a43db2f4ff6 Guest Applications  applicationProxy       False
    a39b9095-8dc8-4d3a-86c3-e7b5c3f0fb84 Application Servers applicationProxy       False
  description: |-
    This command retrieves all connector groups.
  summary: ""
- title: 'Example 2: Retrieve a specific connector group'
  code: |-
    PS C:\> Get-EntraApplicationProxyConnectorGroup -Id a39b9095-8dc8-4d3a-86c3-e7b5c3f0fb84

    Id                                   Name                ConnectorGroupType IsDefault
    --                                   ----                ------------------ ---------
    a39b9095-8dc8-4d3a-86c3-e7b5c3f0fb84 Application Servers applicationProxy       False
  description: |-
    This command retrieves a specific connector group.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: All
  description: |+
    List all pages.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Specifies an oData v3.0 filter statement.
    This parameter controls which objects are returned.
    Details on querying with oData can be found here: https://www.odata.org/documentation/odata-version-3-0/odata-version-3-0-core-protocol/#queryingcollections

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    The ID of the specific connector group.
    You can find this by running the command without this parameter to get the desired ID, or by going into the portal and viewing connector group details.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SearchString
  description: |+
    Specifies the search string.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Top
  description: |+
    Specifies the maximum number of records to return.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Get-EntraApplicationProxyConnectorGroup
name: Get-EntraApplicationProxyConnectorGroup
description: |-
  The Get-EntraApplicationProxyConnectorGroup cmdlet retrieves a list of all connector groups, or if specified, details of the specified connector group.
metadata:
  title: Get-EntraApplicationProxyConnectorGroup
  description: This article provides details on the Get-EntraApplicationProxyConnectorGroup command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/27/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
