### YamlMime:PowershellCmdlet
summary: |-
  Get members from applicationProxyConnectorGroup.
module: Microsoft.Graph.Entra.Get-EntraApplicationProxyConnectorGroupMember
notes: |-
  ## RELATED LINKS
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System. Nullable`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="" data-throw-if-not-resolved="False" /><span>[</span><xref href="System. Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" data-throw-if-not-resolved="False" /><span>]</span><span>]</span>
  description: ""
- name: <xref href="System. Nullable`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" data-throw-if-not-resolved="False" /><span>]</span><span>]</span>
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-EntraApplicationProxyConnectorGroupMember
   -Id <String> 
   [-All] 
   [-Top <Int32>] 
   [-Filter <String>]
   [<CommonParameters>]
examples:
- title: 'Example 1: Get members from applicationProxyConnectorGroup'
  code: |-
    PS C:\> Get-EntraApplicationProxyConnectorGroupMember -Id 87ffe1e2-6313-4a22-93eb-da1eb8a2bf8d

    Name                           Value
    ----                           -----
    id                             147bd8b4-2134-4454-8f2a-1da81cf27917
    externalIp                     3.7.211.5
    machineName                    PERE-VARSHAM-FULLSTAK
    version                        1.5.3437.0
    status                         active
  description: ""
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: All
  description: |+
    List all pages.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Specifies an oData v3.0 filter statement. This parameter controls which objects are returned.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    Specifies the ID of user in Microsoft Entra ID.
  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Top
  description: |+
    Specifies the maximum number of records to return.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Get-EntraApplicationProxyConnectorGroupMember.
name: Get-EntraApplicationProxyConnectorGroupMember.
description: |-
  Get members from applicationProxyConnectorGroup.
metadata:
  title: Get-EntraApplicationProxyConnectorGroupMember.
  description: This article provides details on the Get-EntraApplicationProxyConnectorGroupMember. Command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/22/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
