### YamlMime:PowershellCmdlet
summary: |-
  Retrieves the list of extension properties on an application object.
module: Microsoft.Graph.Entra
notes: ""
inputs:
- name: <xref href="string" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Open.MSGraph.Model.GetExtensionPropertiesResponse" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-EntraMSApplicationExtensionProperty
  href: New-EntraMSApplicationExtensionProperty.yml
- text: Remove-EntraMSApplicationExtensionProperty
  href: Remove-EntraMSApplicationExtensionProperty.yml
syntaxes:
- >-
  Get-EntraMSApplicationExtensionProperty 
   -ObjectId <String> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Get extension properties.'
  code: |-
    PS C:\>Get-EntraMSApplicationExtensionProperty -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84"

    DeletedDateTime Id                                   AppDisplayName DataType IsSyncedFromOnPremises Name                                                     TargetObjects
    --------------- --                                   -------------- -------- ---------------------- ----                                                     -------------
                    9978e52f-1499-4a11-aead-95df460ffa0b                String   False                  extension_418f12ad979549bbaebda0102973258b_NewAttribute2 {}
                    76ff06dc-65cb-4a9b-bf66-5b8e20aa8abf                String   False                  extension_418f12ad979549bbaebda0102973258b_NewAttribute1 {}
                    b901db71-2d86-454b-b2f7-fd1dfbfceac9                String   False                  extension_418f12ad979549bbaebda0102973258b_NewAttribute  {}
  description: |-
    This command gets the extension properties for the specified application in Microsoft Entra ID.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique identifier of the object specific Microsoft Entra ID object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Get-EntraMSApplicationExtensionProperty
name: Get-EntraMSApplicationExtensionProperty
description: |-
  Retrieves the list of extension properties on an application object.
metadata:
  title: Get-EntraMSApplicationExtensionProperty
  description: This article provides details on the Get-EntraMSApplicationExtensionProperty command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/14/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
