### YamlMime:PowershellCmdlet
summary: |-
  Gets an application.
module: Microsoft.Graph.Entra.Get-EntraApplication
notes: ""
links:
- text: New-EntraApplication
  href: New-EntraApplication.yml
- text: Remove-EntraApplication
  href: Remove-EntraApplication.yml
- text: Set-EntraApplication
  href: Set-EntraApplication.yml
syntaxes:
- >-
  Get-EntraApplication 
   [-Filter <String>] 
   [-All] 
   [-Top <Int32>] 
   [<CommonParameters>]
- >-
  Get-EntraApplication 
   [-SearchString <String>] 
   [-All] 
   [<CommonParameters>]
- >-
  Get-EntraApplication 
   -ObjectId <String> 
   [-All] 
   [<CommonParameters>]
examples:
- title: 'Example 1: Get an application by ObjectId'
  code: |-
    PS C:\>Get-EntraApplication -ObjectId "faeae1cc-7353-4fe6-9eea-9c0ddee701f1"

    DisplayName         Id                                   AppId                                SignInAudience PublisherDomain
    -----------         --                                   -----                                -------------- ---------------
    ToGraph_443democc3c faeae1cc-7353-4fe6-9eea-9c0ddee701f1 ad1ca67f-4dbc-48cc-b437-dd289c58f464 AzureADMyOrg   M365x99297270.onmicrosoft.com
  description: |-
    This example demonstrates how to retrieve specific application by providing ID.  
    This command gets an application for the specified ObjectId.
  summary: ""
- title: 'Example 2: Get all applications'
  code: |-
    PS C:\>Get- Get-EntraApplication -All

    DisplayName         Id                                   AppId                                SignInAudience                     PublisherDomain
    -----------         --                                   -----                                --------------                     ---------------
    test app            010cc9b5-fce9-485e-9566-c68debafac5f 5f783237-3457-45d8-93e7-a0edb1cfbfd1 AzureADandPersonalMicrosoftAccount M365x99297270.onmicrosoft.com
    ToGraph_443DEM      02228a68-e98d-4b37-bc69-e2eaf8d324e9 3ee2fcac-fa2b-4080-a8fe-442c6536ca94 AzureADMyOrg                       M365x99297270.onmicrosoft.com
    test adms           03a1489a-70ff-43e0-85f1-236e73088406 9f795b31-e4b5-4ca7-a333-6c0890d62e3c AzureADandPersonalMicrosoftAccount M365x99297270.onmicrosoft.com
    test adms app azure 04080e6b-ade2-4f5e-84c5-748557d17839 f4778f5a-90a2-4a31-b9d4-b137da0848b3 AzureADandPersonalMicrosoftAccount M365x99297270.onmicrosoft.com
    test adms2          049c66c6-df55-4694-b024-d07863a3f5dc 418f12ad-9795-49bb-aebd-a0102973258b AzureADandPersonalMicrosoftAccount M365x99297270.onmicrosoft.com
  description: |-
    This example demonstrates how to get all applications from Microsoft Entra ID.  
    This command gets the all applications in Microsoft Entra ID.
  summary: ""
- title: 'Example 3: Get top five applications'
  code: |-
    PS C:\>Get-EntraApplication -Top 5

    DisplayName         Id                                   AppId                                SignInAudience                     PublisherDomain
    -----------         --                                   -----                                --------------                     ---------------
    test app            010cc9b5-fce9-485e-9566-c68debafac5f 5f783237-3457-45d8-93e7-a0edb1cfbfd1 AzureADandPersonalMicrosoftAccount M365x99297270.onmicrosoft.com
    ToGraph_443DEM      02228a68-e98d-4b37-bc69-e2eaf8d324e9 3ee2fcac-fa2b-4080-a8fe-442c6536ca94 AzureADMyOrg                       M365x99297270.onmicrosoft.com
    test adms           03a1489a-70ff-43e0-85f1-236e73088406 9f795b31-e4b5-4ca7-a333-6c0890d62e3c AzureADandPersonalMicrosoftAccount M365x99297270.onmicrosoft.com
    test adms app azure 04080e6b-ade2-4f5e-84c5-748557d17839 f4778f5a-90a2-4a31-b9d4-b137da0848b3 AzureADandPersonalMicrosoftAccount M365x99297270.onmicrosoft.com
    test adms2          049c66c6-df55-4694-b024-d07863a3f5dc 418f12ad-9795-49bb-aebd-a0102973258b AzureADandPersonalMicrosoftAccount M365x99297270.onmicrosoft.com
  description: |-
    This example demonstrates how to get top five applications from Microsoft Entra ID.  
    This command gets the top five applications.
  summary: ""
- title: 'Example 4: Get an application by display name'
  code: |-
    PS C:\>Get-EntraApplication -Filter "DisplayName eq 'ToGraph_443DEMO'"

    DisplayName     Id                                   AppId                                SignInAudience PublisherDomain
    -----------     --                                   -----                                -------------- ---------------
    ToGraph_443DEMO 5e1ac4d3-015e-404a-87df-b108a9a7f924 d92f1688-37a7-4b2d-9db4-7efdecd4db10 AzureADMyOrg   M365x99297270.onmicrosoft.com
  description: |-
    In this example, we retrieve application by userPrincipalName from Microsoft Entra ID.   
    This command gets an application by its display name.
  summary: ""
- title: 'Example 5: Search among retrieved applications'
  code: |-
    PS C:\>Get-EntraApplication -SearchString "My new application 2"

    DisplayName          Id                                   AppId                                SignInAudience                     PublisherDomain
    -----------          --                                   -----                                --------------                     ---------------
    My new application 2 88a329d6-9a3d-46bb-bd24-8ba1e218d4f5 b36127fd-3bca-4e1c-8698-78d26782ed65 AzureADandPersonalMicrosoftAccount M365x99297270.onmicrosoft.com
  description: |-
    This example demonstrates how to retrieve applications for specific string from Microsoft Entra ID.    
    This cmdlet gets all applications that match the value of SearchString against the first characters in DisplayName.
  summary: ""
- title: 'Example 6: Retrieve an application by identifierUris'
  code: |-
    Get-EntraApplication -Filter "identifierUris/any(uri:uri eq 'http://wingtips.wingtiptoysonline.com')"
  description: |-
    This example demonstrates how to retrieve applications by its identifierUris from Microsoft Entra ID.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: All
  description: |+
    List all pages.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Specifies an oData v3.0 filter statement.
    This parameter controls which objects are returned.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of an application in Microsoft Entra ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SearchString
  description: |+
    Specifies a search string.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Top
  description: |+
    Specifies the maximum number of records to return.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Get-EntraApplication.
name: Get-EntraApplication.
description: |-
  The Get-EntraApplication cmdlet gets a Microsoft Entra ID application.
metadata:
  title: Get-EntraApplication.
  description: This article provides details on the Get-EntraApplication command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/18/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
