### YamlMime:PowershellCmdlet
summary: |-
  Retrieve the service endpoint of an application.
module: Microsoft.Graph.Entra.Get-EntraApplicationServiceEndpoint
notes: |-
  ## RELATED LINKS
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    System.Nullable\`1\[\[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\]\] System.Nullable\`1\[\[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\]\]
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-EntraApplicationServiceEndpoint
   -ObjectId <String>
   [-All]
   [-Top <Int32>]
   [<CommonParameters>]
examples:
- title: 'Example 1: Retrieve the application service endpoint by ID'
  code: |-
    PS C:\WINDOWS\system32> Get-EntraApplicationServiceEndpoint -ObjectId 79592454-dea7-4660-9d91-f1768e5055ac
  description: |-
    This example demonstrates how to retrieve service endpoint of the application that is specified through the Object ID parameter.
  summary: ""
- title: 'Example 2: Get all service endpoints'
  code: |-
    PS C:\WINDOWS\system32> Get-EntraApplicationServiceEndpoint -ObjectId 79592454-dea7-4660-9d91-f1768e5055ac -All
  description: |-
    This example demonstrates how to retrieve all service endpoints of a specified application.
  summary: ""
- title: 'Example 2: Get top five service endpoints'
  code: |-
    PS C:\WINDOWS\system32> Get-EntraApplicationServiceEndpoint -ObjectId 79592454-dea7-4660-9d91-f1768e5055ac -Top 5
  description: |-
    This example demonstrates how to retrieve five service endpoints of a specified application.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: All
  description: |+
    Return all service endpoints.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the object ID of the application for which the service endpoint is retrieved.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Top
  description: |+
    Specifies the maximum number of results that are returned.
    The default is 100.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Get-EntraApplicationServiceEndpoint.
name: Get-EntraApplicationServiceEndpoint.
description: |-
  This cmdlet retrieves the service endpoint(s) of an application.
  The service endpoint entity contains service discovery information.
  The serviceEndpoints property of the Application entity is of type ServiceEndpoint.
  Other services can use the information stored in the ServiceEndpoint entity to find this service and its addressable endpoints.
metadata:
  title: Get-EntraApplicationServiceEndpoint.
  description: This article provides details on the Get-EntraApplicationServiceEndpoint command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/04/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
