### YamlMime:PowershellCmdlet
summary: |-
  Retrieves the list of owners for an application object.
module: Microsoft.Graph.Entra
notes: ""
inputs:
- name: <xref href="Bool?" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Int?" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Open.MSGraph.Model.GetDirectoryObjectsResponse" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-EntraMSApplicationOwner
  href: Add-EntraMSApplicationOwner.yml
- text: Remove-EntraMSApplicationOwner
  href: Remove-EntraMSApplicationOwner.yml
syntaxes:
- >-
  Get-EntraMSApplicationOwner 
   -ObjectId <String> 
   [-All] 
   [-Top <Int32>] 
   [<CommonParameters>]
examples:
- title: 'Example 1: Get the owners of an application.'
  code: |-
    PS C:\>Get-EntraMSApplicationOwner -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84"

    Id                                   DeletedDateTime
    --                                   ---------------
    412be9d1-1460-4061-8eed-cca203fcb215
    abd3d0d8-62c9-47ea-932e-f80d413c7808
    cbf777a2-1ed5-4ea5-80bf-aad80d0a384e
  description: |-
    This command gets the owner of an application.
  summary: ""
- title: 'Example 2: Get the owners of an application using all parameter.'
  code: |-
    PS C:\>Get-EntraMSApplicationOwner -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -All

    Id                                   DeletedDateTime
    --                                   ---------------
    412be9d1-1460-4061-8eed-cca203fcb215
    abd3d0d8-62c9-47ea-932e-f80d413c7808
    cbf777a2-1ed5-4ea5-80bf-aad80d0a384e
  description: |-
    This command gets the owner of an application using all parameter.
  summary: ""
- title: 'Example 3: Get top two owners of an application.'
  code: |-
    PS C:\>Get-EntraMSApplicationOwner -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -Top 2

    Id                                   DeletedDateTime
    --                                   ---------------
    412be9d1-1460-4061-8eed-cca203fcb215
    abd3d0d8-62c9-47ea-932e-f80d413c7808
  description: |-
    This command gets top two owners of an application.
  summary: ""
parameters:
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: All
  description: |+
    List all pages.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of an application in Microsoft Entra ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Top
  description: |+
    Specifies the maximum number of records to return.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Get-EntraMSApplicationOwner
name: Get-EntraMSApplicationOwner
description: |-
  Retrieves the list of owners for an application object.
metadata:
  title: Get-EntraMSApplicationOwner
  description: This article provides details on the Get-EntraMSApplicationOwner command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/14/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
