### YamlMime:PowershellCmdlet
summary: |-
  Gets the directory synchronization settings.
module: Microsoft.Graph.Entra
notes: ""
inputs:
- name: <xref href="System.Nullable`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.Guid, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" data-throw-if-not-resolved="False" /><span>]</span><span>]</span>
  description: ""
links:
- text: Set-EntraDirSyncConfiguration
  href: Set-EntraDirSyncConfiguration.yml
syntaxes:
- >-
  Get-EntraDirSyncConfiguration 
   [-TenantId <Guid>] 
   [<CommonParameters>]
examples:
- title: 'Example 1: Get directory synchronization settings'
  code: |-
    PS C:\> Get-EntraDirSyncConfiguration

    AccidentalDeletionThreshold DeletionPreventionType
    --------------------------- ----------------------
                            500 enabledForCount
  description: |-
    This command gets directory synchronization settings.
  summary: ""
- title: 'Example 2: Get directory synchronization settings by TenantId'
  code: |-
    PS C:\> Get-EntraDirSyncConfiguration -TenantId "d5aec55f-2d12-4442-8d2f-ccca95d4390e"

    AccidentalDeletionThreshold DeletionPreventionType
    --------------------------- ----------------------
                            500 enabledForCount
  description: |-
    This command gets directory synchronization settings by TenantId.
  summary: ""
parameters:
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: TenantId
  description: |+
    The unique ID of the tenant to perform the operation on. 
    If this isn't provided then it defaults to the tenant of the current user. 
    This parameter is only applicable to partner users.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Get-EntraDirSyncConfiguration
name: Get-EntraDirSyncConfiguration
description: |-
  The Get-EntraDirSyncConfiguration cmdlet gets the directory synchronization settings.
metadata:
  title: Get-EntraDirSyncConfiguration
  description: This article provides details on the Get-EntraDirSyncConfiguration command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/28/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
