### YamlMime:PowershellCmdlet
summary: |-
  Retrieves the list of previously deleted applications.
module: Microsoft.Graph.Entra
notes: |-
  ## RELATED LINKS
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    System.Nullable\`1\[\[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\]\] System.Nullable\`1\[\[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\]\]
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-EntraDeletedApplication 
   [-Filter <String>] 
   [-All] 
   [-Top <Int32>] 
   [<CommonParameters>]
- >-
  Get-EntraDeletedApplication 
   [-SearchString <String>] 
   [-All] 
   [<CommonParameters>]
examples:
- title: 'Example 1: Get list of deleted applications.'
  code: |-
    PS C:\> Get-EntraDeletedApplication

    DisplayName Id                                   AppId                                SignInAudience PublisherDomain
    ----------- --                                   -----                                -------------- ---------------
    TestApp1    01157307-373c-47b0-889a-3bc57033d73e 9c17362d-20b6-4572-bb6f-600e57c840e5 AzureADMyOrg   contoso.com
    TestApp2    021b7606-8ad9-4a99-a305-32c7e9d4ef42 ed463582-f4c6-401e-963c-8b1207f11ff0 AzureADMyOrg   contoso.com
    TestApp3    028f64e2-df14-4211-95ac-d97012de48e4 6bb88aa2-5525-4711-9091-0379c9119547 AzureADMyOrg   contoso.com
    TestApp4    04a4b3be-a050-4627-83e3-0cbe80be8946 e29d0e59-86f7-41db-9d72-cd007dff50ea AzureADMyOrg   contoso.com
  description: |-
    This cmdlet retrieves the list of deleted applications.
  summary: ""
- title: 'Example 2: Get list of deleted applications using All parameter.'
  code: |-
    PS C:\> Get-EntraDeletedApplication -All

    DisplayName Id                                   AppId                                SignInAudience PublisherDomain
    ----------- --                                   -----                                -------------- ---------------
    TestApp1    01157307-373c-47b0-889a-3bc57033d73e 9c17362d-20b6-4572-bb6f-600e57c840e5 AzureADMyOrg   contoso.com
    TestApp2    021b7606-8ad9-4a99-a305-32c7e9d4ef42 ed463582-f4c6-401e-963c-8b1207f11ff0 AzureADMyOrg   contoso.com
    TestApp3    028f64e2-df14-4211-95ac-d97012de48e4 6bb88aa2-5525-4711-9091-0379c9119547 AzureADMyOrg   contoso.com
    TestApp4    04a4b3be-a050-4627-83e3-0cbe80be8946 e29d0e59-86f7-41db-9d72-cd007dff50ea AzureADMyOrg   contoso.com
  description: |-
    This cmdlet retrieves the list of deleted applications using All parameter.
  summary: ""
- title: 'Example 3: Get top two deleted applications.'
  code: |-
    PS C:\> Get-EntraDeletedApplication -Top 2

    DisplayName Id                                   AppId                                SignInAudience PublisherDomain
    ----------- --                                   -----                                -------------- ---------------
    TestApp1    01157307-373c-47b0-889a-3bc57033d73e 9c17362d-20b6-4572-bb6f-600e57c840e5 AzureADMyOrg   contoso.com
    TestApp2    021b7606-8ad9-4a99-a305-32c7e9d4ef42 ed463582-f4c6-401e-963c-8b1207f11ff0 AzureADMyOrg   contoso.com
  description: |-
    This cmdlet retrieves top two deleted applications.
  summary: ""
- title: 'Example 4: Get deleted applications using SearchString parameter.'
  code: |-
    PS C:\> Get-EntraDeletedApplication -SearchString 'TestApp1'

    DisplayName Id                                   AppId                                SignInAudience PublisherDomain
    ----------- --                                   -----                                -------------- ---------------
    TestApp1    01157307-373c-47b0-889a-3bc57033d73e 9c17362d-20b6-4572-bb6f-600e57c840e5 AzureADMyOrg   contoso.com
  description: |-
    This cmdlet retrieves deleted applications using SearchString parameter.
  summary: ""
- title: 'Example 5: Get deleted applications filter by display name.'
  code: |-
    PS C:\> Get-EntraDeletedApplication -Filter "DisplayName contains 'TestApp1'"

    DisplayName Id                                   AppId                                SignInAudience PublisherDomain
    ----------- --                                   -----                                -------------- ---------------
    TestApp1    01157307-373c-47b0-889a-3bc57033d73e 9c17362d-20b6-4572-bb6f-600e57c840e5 AzureADMyOrg   contoso.com
  description: |-
    This cmdlet retrieves deleted applications having specified display name.
  summary: ""
parameters:
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: All
  description: |+
    List all pages.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Retrieve only those deleted applications that satisfy the filter.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SearchString
  description: |+
    Retrieve only those applications that satisfy the -SearchString value.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Top
  description: |+
    The maximum number of applications returned by this cmdlet.
    The default value is 100.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Get-EntraDeletedApplication
name: Get-EntraDeletedApplication
description: |-
  Retrieves the list of previously deleted applications.
metadata:
  title: Get-EntraDeletedApplication
  description: This article provides details on the Get-EntraDeletedApplication command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/15/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
