### YamlMime:PowershellCmdlet
summary: |-
  The Get-EntraApplicationProxyConnectorMemberOf command gets the ConnectorGroup that the specified Connector is a member of.
module: Microsoft.Graph.Entra.Get-EntraApplicationProxyConnectorMemberOf
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-EntraApplicationProxyConnectorMemberOf 
   -Id <String> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Gets the ConnectorGroup'
  code: |-
    PS C:\> Get-EntraApplicationProxyConnectorMemberOf -Id 4c8b06e7-9751-41d5-8e5e-48e9b9bc2c66

    Id                                   Name                ConnectorGroupType IsDefault
    --                                   ----                ------------------ ---------
    a39b9095-8dc8-4d3a-86c3-e7b5c3f0fb84 Application Servers applicationProxy       False
  description: |-
    This example demonstrates how to retrieve the ConnectorGroup that the specified Connector is a member of.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    The ID of the connector.
    You can find ID by running Get-EntraApplicationProxyConnector.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Get-EntraApplicationProxyConnectorMemberOf.
name: Get-EntraApplicationProxyConnectorMemberOf.
description: |-
  The Get-EntraApplicationProxyConnectorMemberOf command gets the ConnectorGroup that the specified Connector is a member of.
  If no group is assigned to the connector, by default it is in 'Default.'
metadata:
  title: Get-EntraApplicationProxyConnectorMemberOf.
  description: This article provides details on the Get-EntraApplicationProxyConnectorMemberOf Command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/27/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
