### YamlMime:PowershellCmdlet
summary: |-
  Gets the password credential for an application.
module: Microsoft.Graph.Entra
notes: ""
syntaxes:
- >-
  Get-EntraApplicationPasswordCredential 
   -ObjectId <String> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Get password credential for specified application.'
  code: |-
    PS C:\>New-EntraApplicationPasswordCredential -ObjectId 3ddd22e7-a150-4bb3-b100-e410dea1cb84

    CustomKeyIdentifier  DisplayName EndDateTime           Hint KeyId                                SecretText StartDateTime
    -------------------  ----------- -----------           ---- -----                                ---------- -------------
    {116, 101, 115, 116}             11/24/2024 6:28:39 AM 123  292e9b65-45db-4fe1-9362-da69c64d8649            11/24/2023 6:28:39 AM
  description: |-
    This command gets the password credential for specified application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The objectID of the application for which to get the password credential.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Get-EntraApplicationPasswordCredential
name: Get-EntraApplicationPasswordCredential
description: |-
  The Get-EntraApplicationPasswordCredential cmdlet gets the password credentials for a Microsoft Entra ID application.
metadata:
  title: Get-EntraApplicationPasswordCredential
  description: This article provides details on the Get-EntraApplicationPasswordCredential command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/14/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
