### YamlMime:PowershellCmdlet
summary: |-
  Gets global public Environments.
module: Microsoft.Graph.Entra
notes: ""
links:
- text: Add-EntraEnvironment
  href: Add-EntraEnvironment.yml
syntaxes:
- >-
  Get-EntraEnvironment 
   [<CommonParameters>]
- >-
  PS C:\>Get-EntraEnvironment 
   -Name <String> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Get a list of public cloud environments'
  code: |-
    PS C:\>Get-EntraEnvironment

    Name , AzureADEndpoint, GraphEndpoint, Type
    ---------         ------------------------------ --------------------------- ---------------
    China    https://login.chinacloudapi.cn    https://microsoftgraph.chinacloudapi.cn Built-in
    Global   https://login.microsoftonline.com https://graph.microsoft.com             Built-in
    USGov    https://login.microsoftonline.us  https://graph.microsoft.us              Built-in
    USGovDoD https://login.microsoftonline.us  https://dod-graph.microsoft.us          Built-in
    Germany  https://login.microsoftonline.de  https://graph.microsoft.de              Built-in                                                                                      {}
  description: |-
    This command retrieves a list of global public Environments.
  summary: ""
- title: 'Example 2: Get a specific environment created.'
  code: |-
    PS C:\>Get-EntraEnvironment -Name "Global"

    Name , AzureADEndpoint, GraphEndpoint, Type

    --------         ------------------ ------------------ --------
    Global   https://login.microsoftonline.com https://graph.microsoft.com             Built-in                                                                                  {}
  description: |-
    This command retrieves an environment with the specified name.
  summary: ""
parameters:
- type: <span>undefined</span>
  name: Name
  description: |+
    Specifies the name of an environment

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Get-EntraEnvironment
name: Get-EntraEnvironment
description: |-
  When you use Connect-Entra, you can choose to target other environments. By default, Connect-Entra targets the global public cloud.
metadata:
  title: Get-EntraEnvironment
  description: This article provides details on the Get-EntraEnvironment command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 05/07/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
