### YamlMime:PowershellCmdlet
summary: |-
  The Get-EntraApplicationProxyConnectorGroupMembers get all the Application Proxy connectors associated with the given connector group.
module: Microsoft.Graph.Entra
notes: |-
  ## RELATED LINKS
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    System.Nullable`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
    System.Nullable`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-EntraApplicationProxyConnectorGroupMembers
   -Id <String>
   [-All]
   [-Top <Int32>]
   [-Filter <String>]
examples:
- title: 'Example 1: Show all the connectors in the group'
  code: |-
    PS C:\> Get-EntraApplicationProxyConnectorGroupMembers -Id ba07e273-6b9e-4567-afe4-efddac32509d

    Id                                   MachineName     ExternalIp   Status
    --                                   -----------     ----------   ------
    969eddd2-ad11-47ca-92ba-4442b9901edf vm-test-010 13.93.84.164 active
    ea4a4b91-aace-4e8b-b81a-b2f6429a477e test-vm-conn1 52.18.9.115 active
  description: |-
    The output of this command, showing all the connectors in the group.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: All
  description: |+
    List all pages.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Specifies an oData v3.0 filter statement. This parameter controls which objects are returned. Details on querying with oData can be found here: https://www.odata.org/documentation/odata-version-3-0/odata-version-3-0-core-protocol/#queryingcollections

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    The ID of the Connector group. This can be found by running the Get-EntraApplicationProxyConnectorGroup command. 

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Top
  description: |+
    Specifies the maximum number of records to return.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Get-EntraApplicationProxyConnectorGroupMembers
name: Get-EntraApplicationProxyConnectorGroupMembers
description: |-
  The Get-EntraApplicationProxyConnectorGroupMembers gets all the Application Proxy connectors associated with the given connector group.
metadata:
  title: Get-EntraApplicationProxyConnectorGroupMembers
  description: This article provides details on the Get-EntraApplicationProxyConnectorGroupMembers command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/27/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
