### YamlMime:PowershellCmdlet
summary: |-
  Gets the owner of an application.
module: Microsoft.Graph.Entra.Get-EntraApplicationOwner
notes: ""
links:
- text: Add-EntraApplicationOwner
  href: Add-EntraApplicationOwner.yml
- text: Remove-EntraApplicationOwner
  href: Remove-EntraApplicationOwner.yml
syntaxes:
- >-
  Get-EntraApplicationOwner 
   -ObjectId <String> 
   [-All] 
   [-Top <Int32>] 
   [<CommonParameters>]
examples:
- title: 'Example 1: Get the owner of an application'
  code: |-
    PS C:\>Get-EntraApplicationOwner -ObjectId "e3108c4d-86ff-4ceb-9429-24e85b4b8cea"

    ageGroup                        :
    onPremisesLastSyncDateTime      :
    creationType                    :
    imAddresses                     : {adelev@m365x99297270.onmicrosoft.com}
    preferredLanguage               :
    mail                            : AdeleV@M365x99297270.OnMicrosoft.com
    securityIdentifier              : S-1-12-1-1093396945-1080104032-2731339150-364051459
    identities                      : {@{signInType=userPrincipalName; issuer=M365x99297270.onmicrosoft.com; issuerAssignedId=AdeleV@M365x99297270.OnMicrosoft.com}}
    consentProvidedForMinor         :
    onPremisesUserPrincipalName     :
  description: |-
    This example demonstrates how to get the owners of an application in Microsoft Entra ID.  
    This command gets the owners of an application.
  summary: ""
- title: 'Example 2: Get all owners of an application'
  code: |-
    PS C:\>Get-EntraApplicationOwner -ObjectId "e3108c4d-86ff-4ceb-9429-24e85b4b8cea" -All

    ageGroup                        :
    onPremisesLastSyncDateTime      :
    creationType                    :
    imAddresses                     : {adelev@m365x99297270.onmicrosoft.com}
    preferredLanguage               :
    mail                            : AdeleV@M365x99297270.OnMicrosoft.com
    securityIdentifier              : S-1-12-1-1093396945-1080104032-2731339150-364051459
    identities                      : {@{signInType=userPrincipalName; issuer=M365x99297270.onmicrosoft.com; issuerAssignedId=AdeleV@M365x99297270.OnMicrosoft.com}}
    consentProvidedForMinor         :
    onPremisesUserPrincipalName     :
  description: |-
    This example demonstrates how to get the all owners of a specified application in Microsoft Entra ID.  
    This command gets the all owners of a specified application.
  summary: ""
- title: 'Example 3: Get top two owners of an application'
  code: |-
    PS C:\>Get-EntraApplicationOwner -ObjectId "e3108c4d-86ff-4ceb-9429-24e85b4b8cea" -Top 2

    ageGroup                        :
    onPremisesLastSyncDateTime      :
    creationType                    :
    imAddresses                     : {adelev@m365x99297270.onmicrosoft.com}
    preferredLanguage               :
    mail                            : AdeleV@M365x99297270.OnMicrosoft.com
    securityIdentifier              : S-1-12-1-1093396945-1080104032-2731339150-364051459
    identities                      : {@{signInType=userPrincipalName; issuer=M365x99297270.onmicrosoft.com; issuerAssignedId=AdeleV@M365x99297270.OnMicrosoft.com}}
    consentProvidedForMinor         :
    onPremisesUserPrincipalName     :
  description: |-
    This example demonstrates how to get the all owners of a specified application in Microsoft Entra ID.  
    This command gets the two owners of a specified application.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: All
  description: |+
    List all pages.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of an application in Microsoft Entra ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Top
  description: |+
    Specifies the maximum number of records to return.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Get-EntraApplicationOwner.
name: Get-EntraApplicationOwner.
description: |-
  The Get-EntraApplicationOwner cmdlet gets an owner of a Microsoft Entra ID application.
metadata:
  title: Get-EntraApplicationOwner.
  description: This article provides details on the Get-EntraApplicationOwner command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/15/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
