### YamlMime:PowershellCmdlet
summary: |-
  Creates a password credential for an application.
module: Microsoft.Graph.Entra
notes: ""
links:
- text: Get-EntraApplicationPasswordCredential
  href: Get-EntraApplicationPasswordCredential.yml
- text: Remove-EntraApplicationPasswordCredential
  href: Remove-EntraApplicationPasswordCredential.yml
syntaxes:
- >-
  New-EntraApplicationPasswordCredential 
   -ObjectId <String> 
   [-StartDate <DateTime>] 
   [-EndDate <DateTime>] 
   [<CommonParameters>]
examples:
- title: 'Example 1: Create a password credential'
  code: |-
    PS C:\>New-EntraApplicationPasswordCredential -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84"

    CustomKeyIdentifier DisplayName EndDateTime          Hint KeyId                                SecretText                    StartDateTime
    ------------------- ----------- -----------          ---- -----                                ----------                    -------------
                                    3/21/2026 9:48:40 AM n34  b30c6289-7903-4a61-97e6-2ada9742fd3b wbBNW8kCuiPjNRg9NX98W_EaU6cqG 3/21/2024 9:48:40 AM
  description: |-
    This command creates new password credential for specified application.
  summary: ""
- title: 'Example 2: Create a password credential using StartDate parameter'
  code: |-
    PS C:\>New-EntraApplicationPasswordCredential -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -StartDate (get-date).AddYears(0)

    CustomKeyIdentifier DisplayName EndDateTime          Hint KeyId                                SecretText                    StartDateTime
    ------------------- ----------- -----------          ---- -----                                ----------                    -------------
                                    3/21/2026 9:48:40 AM n34  b30c6289-7903-4a61-97e6-2ada9742fd3b wbBNW8kCuiPjNRg9NX98W_EaU6cqG 3/21/2024 9:48:40 AM
  description: |-
    This command creates new password credential for specified application.
  summary: ""
- title: 'Example 3: Create a password credential using EndDate parameter'
  code: |-
    PS C:\>New-EntraApplicationPasswordCredential -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -EndDate (get-date).AddYears(2)

    CustomKeyIdentifier DisplayName EndDateTime          Hint KeyId                                SecretText                    StartDateTime
    ------------------- ----------- -----------          ---- -----                                ----------                    -------------
                                    3/21/2026 9:48:40 AM n34  b30c6289-7903-4a61-97e6-2ada9742fd3b wbBNW8kCuiPjNRg9NX98W_EaU6cqG 3/21/2024 9:48:40 AM
  description: |-
    This command creates new password credential for specified application.
  summary: ""
parameters:
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: EndDate
  description: |+
    The date and time at which the password expires.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of a user in Microsoft Entra ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: StartDate
  description: |+
    The date and time at which the password becomes valid.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.New-EntraApplicationPasswordCredential
name: New-EntraApplicationPasswordCredential
description: |-
  The New-EntraApplicationPasswordCredential cmdlet creates a password credential for an application in Microsoft Entra ID.
metadata:
  title: New-EntraApplicationPasswordCredential
  description: This article provides details on the New-EntraApplicationPasswordCredential command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/21/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
