### YamlMime:PowershellCmdlet
summary: |-
  Creates an extension property on an application object.
module: Microsoft.Graph.Entra
notes: ""
inputs:
- name: <xref href="String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
outputs:
- name: <xref href="Microsoft.Open.MSGraph.Model.ExtensionProperty" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-EntraMSApplicationExtensionProperty
  href: Get-EntraMSApplicationExtensionProperty.yml
- text: Remove-EntraMSApplicationExtensionProperty
  href: Remove-EntraMSApplicationExtensionProperty.yml
syntaxes:
- >-
  New-EntraMSApplicationExtensionProperty 
   -ObjectId <String> 
   [-DataType <String>] 
   [-TargetObjects <System.Collections.Generic.List`1[System.String]>] 
   [-Name <String>] 
   [<CommonParameters>]
examples:
- title: 'Example 1: Create an extension property'
  code: |-
    PS C:\>New-EntraMSApplicationExtensionProperty -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -DataType "string" -Name "NewAttribute" -TargetObjects "Application"

    ObjectId                             Name                                                    TargetObjects
    --------                             ----                                                    -------------
    3ddd22e7-a150-4bb3-b100-e410dea1cb84 extension_36ee4c6c081240a2b820b22ebd02bce3_NewAttribute {}
  description: |-
    This command creates an application extension property of the string type for the specified object.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DataType
  description: |+
    Specifies the data type of the extension property.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies the data type of the extension property.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique identifier of the object specific Microsoft Entra ID object

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: TargetObjects
  description: |+
    Specifies target objects.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.New-EntraMSApplicationExtensionProperty
name: New-EntraMSApplicationExtensionProperty
description: |-
  Creates an extension property on an application object.
metadata:
  title: New-EntraMSApplicationExtensionProperty
  description: This article provides details on the New-EntraMSApplicationExtensionProperty command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/06/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
