### YamlMime:PowershellCmdlet
summary: |-
  Adds a strong password to an application.
module: Microsoft.Graph.Entra
notes: ""
inputs:
- name: <xref href="String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.PasswordCredential" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Open.MSGraph.Model.PasswordCredential" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Remove-EntraMSApplicationPassword
  href: Remove-EntraMSApplicationPassword.yml
syntaxes:
- >-
  New-EntraMSApplicationPassword 
   -ObjectId <String> 
   -PasswordCredential <PasswordCredential> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Add a password to an application'
  code: |-
    PS C:\> New-EntraMSApplicationPassword -ObjectId 14a3f1ac-46a7-4d00-b1ca-0b2b84f033c2 -PasswordCredential @{ displayname = "mypassword" }

    CustomKeyIdentifier DisplayName EndDateTime           Hint KeyId                                SecretText                       StartDateTime
    ------------------- ----------- -----------           ---- -----                                ----------                       -------------
                        mypassword  10/28/2021 3:57:37 PM EQ:  024c4c6e-87c3-4473-8e36-650f16bb730d EQ:A-s45?Rt9/3Bp?7]-7__IO]3AG09E 10/28/2019 3:57:37 PM
  description: |-
    This command adds a password to the specified application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique identifier of the object specific Microsoft Entra ID object

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PasswordCredential" data-throw-if-not-resolved="False" />
  name: PasswordCredential
  isRequired: true
  description: |+
    Represents a password credential associated with an application or a service principal.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.New-EntraMSApplicationPassword
name: New-EntraMSApplicationPassword
description: |-
  Adds a strong password to an application.
metadata:
  title: New-EntraMSApplicationPassword
  description: This article provides details on the New-EntraMSApplicationPassword command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/26/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
