### YamlMime:PowershellCmdlet
summary: |-
  Creates (registers) a new application object.
module: Microsoft.Graph.Entra
notes: ""
inputs:
- name: <xref href="Boolean" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.ApiApplication" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.InformationalUrl" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.OptionalClaims" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.ParentalControlSettings" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.PublicClientApplication" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.WebApplication" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.Add-in" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.AppRole" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.KeyCredential" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.PasswordCredential" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.RequiredResourceAccess" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
- name: <xref href="System. Nullable`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.Boolean" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
outputs:
- name: <xref href="Microsoft.Open.MSGraph.Model.MsApplication" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-EntraMSApplication
  href: Get-EntraMSApplication.yml
- text: Remove-EntraMSApplication
  href: Remove-EntraMSApplication.yml
- text: Set-EntraMSApplication
  href: Set-EntraMSApplication.yml
- text: Get-EntraMSApplication
  href: Get-EntraMSApplication.yml
- text: Remove-EntraMSApplication
  href: Remove-EntraMSApplication.yml
- text: Set-EntraMSApplication
  href: Set-EntraMSApplication.yml
syntaxes:
- >-
  New-EntraMSApplication 
   -DisplayName <String>
   [-AddIns <System.Collections.Generic.List`1[Microsoft.Open.MSGraph.Model.AddIn]>]
   [-PasswordCredentials <System.Collections.Generic.List`1[Microsoft.Open.MSGraph.Model.PasswordCredential]>]
   [-TokenEncryptionKeyId <String>] 
   [-SignInAudience <String>]
   [-KeyCredentials <System.Collections.Generic.List`1[Microsoft.Open.MSGraph.Model.KeyCredential]>]
   [-ParentalControlSettings <ParentalControlSettings>]
   [-IdentifierUris <System.Collections.Generic.List`1[System.String]>]
   [-AppRoles <System.Collections.Generic.List`1[Microsoft.Open.MSGraph.Model.AppRole]>]
   [-PublicClient <PublicClientApplication>] 
   [-InformationalUrl <InformationalUrl>]
   [-Tags <System.Collections.Generic.List`1[System.String]>] 
   [-Api <ApiApplication>]
   [-OptionalClaims <OptionalClaims>] 
   [-GroupMembershipClaims <String>] 
   [-Web <WebApplication>]
   [-IsFallbackPublicClient <Boolean>] 
   [-IsDeviceOnlyAuthSupported <Boolean>]
   [-RequiredResourceAccess <System.Collections.Generic.List`1[Microsoft.Open.MSGraph.Model.RequiredResourceAccess]>]
   [<CommonParameters>]
examples:
- title: 'Example 1: Create an application'
  code: |-
    PS C:\> New-EntraMSApplication -DisplayName "My new application"

    DisplayName        Id                                   AppId                                SignInAudience PublisherDomain
    -----------        --                                   -----                                -------------- ---------------
    My new application 7b31c9a5-5ee8-4bc6-8c9f-c0f572ccb494 9149506f-6ac5-40c8-80ae-0bc05378da66 AzureADMyOrg   M365x99297270.mail.onmicrosoft.com
  description: |-
    This command creates an application in Microsoft Entra ID.
  summary: ""
- title: 'Example 2: Create an application using IdentifierUris parameter'
  code: |-
    PS C:\> New-EntraMSApplication -DisplayName "My new application" -IdentifierUris "https://mynewapp.contoso.com"

    DisplayName        Id                                   AppId                                SignInAudience PublisherDomain
    -----------        --                                   -----                                -------------- ---------------
    My new application 7b31c9a5-5ee8-4bc6-8c9f-c0f572ccb494 9149506f-6ac5-40c8-80ae-0bc05378da66 AzureADMyOrg   M365x99297270.mail.onmicrosoft.com
  description: |-
    This command creates an application in Microsoft Entra ID.
  summary: ""
- title: 'Example 3: Create an application using AddIns parameter'
  code: |-
    PS C:\> $addin = New-Object Microsoft.Open.MSGraph.Model.AddIn
    PS C:\> $addin.Type = 'testtype'
    PS C:\> $addinproperties = New-Object System.collections.Generic.List[Microsoft.Open.MSGraph.Model.KeyValue]
    PS C:\> $addinproperties.Add([Microsoft.Open.MSGraph.Model.KeyValue]@{ Key = "key"; Value = "value" })
    PS C:\> $addin.Properties = $addinproperties
    PS C:\> New-EntraMSApplication -DisplayName "My new application" -AddIns $addin

    DisplayName        Id                                   AppId                                SignInAudience PublisherDomain
    -----------        --                                   -----                                -------------- ---------------
    My new application 7b31c9a5-5ee8-4bc6-8c9f-c0f572ccb494 9149506f-6ac5-40c8-80ae-0bc05378da66 AzureADMyOrg   M365x99297270.mail.onmicrosoft.com
  description: |-
    This command creates an application in Microsoft Entra ID.
  summary: ""
parameters:
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.AddIn" data-throw-if-not-resolved="False" /><span>]</span>
  name: AddIns
  description: |+
    Defines custom behavior that a consuming service can use to call an app in specific contexts.
    For example, applications that can render file streams might set the addIns property for its "FileHandler" functionality.
    This lets services like Office 365 call the application in the context of a document the user is working on.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ApiApplication" data-throw-if-not-resolved="False" />
  name: Api
  description: |+
    Specifies settings for an application that implements a web API.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.AppRole" data-throw-if-not-resolved="False" /><span>]</span>
  name: AppRoles
  description: |+
    The collection of application roles that an application might declare.
    These roles can be assigned to users, groups, or service principals.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayName
  isRequired: true
  description: |+
    Specifies the display name of the application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GroupMembershipClaims
  description: |+
    Configures the groups claim issued in a user or OAuth 2.0 access token that the application expects.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: IdentifierUris
  description: |+
    User-defined URIs that uniquely identify a Web application within its Microsoft Entra ID tenant, or within a verified custom domain (see "Domains" tab in the Azure classic portal) if the application is multitenant.

    The first element is populated from the Web application's "APP ID URI" field if updated via the Azure classic portal (or respective Microsoft Entra ID PowerShell cmdlet parameter).
    Extra URIs can be added via the application manifest; see Understanding the Microsoft Entra ID Application Manifest for details.
    This collection is also used to populate the Web application's servicePrincipalNames collection.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="InformationalUrl" data-throw-if-not-resolved="False" />
  name: InformationalUrl
  description: |+
    Basic profile information of the application such as app's marketing, support, terms of service and privacy statement URLs.
    The terms of service and privacy statement are surfaced to users through the user consent experience.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsDeviceOnlyAuthSupported
  description: |+
    Specifies if the application supports authentication using a device token.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsFallbackPublicClient
  description: |+
    Specifies the fallback application type as public client, such as an installed application running on a mobile device.
    The default value is false that means the fallback application type is confidential client such as web app.
    There are certain scenarios where Microsoft Entra ID can't determine the client application type (for example,
    ROPC flow where it's configured without specifying a redirect URI).
    In those cases Microsoft Entra ID interprets the application type based on the value of this property.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.KeyCredential" data-throw-if-not-resolved="False" /><span>]</span>
  name: KeyCredentials
  description: |+
    The collection of key credentials associated with the application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="OptionalClaims" data-throw-if-not-resolved="False" />
  name: OptionalClaims
  description: |+
    Application developers can configure optional claims in their Microsoft Entra ID apps to specify which claims they want in tokens sent to their application by the Microsoft security token service.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ParentalControlSettings" data-throw-if-not-resolved="False" />
  name: ParentalControlSettings
  description: |+
    Specifies parental control settings for an application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.PasswordCredential" data-throw-if-not-resolved="False" /><span>]</span>
  name: PasswordCredentials
  description: |+
    The collection of password credentials associated with the application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PublicClientApplication" data-throw-if-not-resolved="False" />
  name: PublicClient
  description: |+
    Specifies whether this application is a public client (such as an installed application running on a mobile device).
    Default is false.

    Specifies whether this application is a public client (such as an installed application running on a mobile device).
    Default is false.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.RequiredResourceAccess" data-throw-if-not-resolved="False" /><span>]</span>
  name: RequiredResourceAccess
  description: |+
    Specifies resources that this application requires access to and the set of OAuth permission scopes and application roles that it needs under each of those resources.
    This preconfiguration of required resource access drives the consent experience.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SignInAudience
  description: |+
    Specifies what Microsoft accounts are supported for the current application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: Tags
  description: |+
    Custom strings that can be used to categorize and identify the application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TokenEncryptionKeyId
  description: |+
    Specifies the keyId of a public key from the keyCredentials collection.
    When configured, Microsoft Entra ID encrypts all the tokens it emits by using the key this property points to.
    The application code that receives the encrypted token must use the matching private key to decrypt the token before it can be used for the signed-in user.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="WebApplication" data-throw-if-not-resolved="False" />
  name: Web
  description: |+
    Specifies settings for a web application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.New-EntraMSApplication
name: New-EntraMSApplication
description: |-
  Creates (registers) a new application object.
metadata:
  title: New-EntraMSApplication
  description: This article provides details on the New-EntraMSApplication command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/22/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
