### YamlMime:PowershellCmdlet
summary: |-
  The New-EntraApplicationProxyApplication cmdlet creates a new application configured for Application Proxy in Microsoft Entra ID.
module: Microsoft.Graph.Entra
notes: |-
  ## RELATED LINKS
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    System.Nullable\`1\[\[Microsoft.Open.MSGraph.Model.ApplicationProxyApplicationObject+ExternalAuthenticationTypeEnum, Microsoft.Open.MS.GraphV10.Client, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null\]\] System.Nullable\`1\[\[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\]\] System.Nullable\`1\[\[Microsoft.Open.MSGraph.Model.ApplicationProxyApplicationObject+ApplicationServerTimeoutEnum, Microsoft.Open.MS.GraphV10.Client, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null\]\]
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  New-EntraApplicationProxyApplication 
    -DisplayName <String> 
    -ExternalUrl <String> 
    -InternalUrl <String>
    [-ExternalAuthenticationType <ExternalAuthenticationTypeEnum>] 
    [-IsTranslateHostHeaderEnabled <Boolean>]
    [-IsHttpOnlyCookieEnabled <Boolean>] 
    [-IsSecureCookieEnabled <Boolean>] 
    [-IsPersistentCookieEnabled <Boolean>]
    [-IsTranslateLinksInBodyEnabled <Boolean>] 
    [-ApplicationServerTimeout <ApplicationServerTimeoutEnum>]
    [-ConnectorGroupId <String>] 
    [<CommonParameters>]
examples:
- title: 'Example 1: Creating a new application with only the basic required settings, and the default domain for applications.'
  code: |-
    PS C:\> New-EntraApplicationProxyApplication -DisplayName "Finance Tracker" -ExternalUrl "https://finance-awcycles.msappproxy.net/" -InternalUrl "https://finance/"

    ExternalAuthenticationType               : AadPreAuthentication
    ApplicationServerTimeout                 : Default
    ExternalUrl                              : https://finance-awcycles.msappproxy.net/
    InternalUrl                              : https://finance/
    IsTranslateHostHeaderEnabled             : True
    IsTranslateLinksInBodyEnabled            : False
    IsOnPremPublishingEnabled                : True
    VerifiedCustomDomainCertificatesMetadata : 
    VerifiedCustomDomainKeyCredential        : 
    VerifiedCustomDomainPasswordCredential   : 
    SingleSignOnSettings                     :
  description: |-
    This command creates a new application with only the basic required settings, and the default domain for applications.
  summary: ""
- title: 'Example 2: Creating a new application that uses a custom domain and sets several optional flags.'
  code: "PS C:\\> New-EntraApplicationProxyApplication -DisplayName \"HR Resources\" -ExternalUrl \"https://hr.adventure-works.com/\" -InternalUrl \"https://hr.adventure-works.com/\" -ApplicationServerTimeout Long\r\n\r\nExternalAuthenticationType               : AadPreAuthentication\r\nApplicationServerTimeout                 : Long\r\nExternalUrl                              : https://hr.adventure-works.com/\r\nInternalUrl                              : https://hr.adventure-works.com/\r\nIsTranslateHostHeaderEnabled             : True\r\nIsTranslateLinksInBodyEnabled            : False\r\nIsOnPremPublishingEnabled                : True\r\nVerifiedCustomDomainCertificatesMetadata : class OnPremisesPublishingVerifiedCustomDomainCertificatesMetadataObject {\r\n                                             Thumbprint: [XXXXX]\r\n                                             SubjectName: [XXXXX]\r\n                                             Issuer: \r\n                                             IssueDate: 11/9/2017 5:54:29\r\n                                             ExpiryDate: 11/9/2019 5:54:29\r\n                                           }\r\n                                           \r\nVerifiedCustomDomainKeyCredential        : \r\nVerifiedCustomDomainPasswordCredential   : \r\nSingleSignOnSettings                     :"
  description: |-
    This command creates a new application that uses a custom domain and sets several optional flags.
  summary: ""
parameters:
- type: <xref href="ApplicationServerTimeoutEnum" data-throw-if-not-resolved="False" />
  name: ApplicationServerTimeout
  description: |+
    Set this value to Long only if your application is slow to authenticate and connect.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: Default, Long
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ConnectorGroupId
  description: |+
    Provide the Id of the Connector group you would like assigned to this application.
    You can find this value by using the [Get-EntraApplicationProxyConnectorGroup](./Get-EntraApplicationProxyConnectorGroup.yml) command.
    Connectors process the remote access to your application, and connector groups help you organize connectors and apps by region, network, or purpose.
    If you don't have any connector groups created yet, your app is assigned to Default.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayName
  isRequired: true
  description: |+
    The display name of the new Application

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ExternalAuthenticationTypeEnum" data-throw-if-not-resolved="False" />
  name: ExternalAuthenticationType
  description: |+
    How Application Proxy verifies users before giving them access to your application. 
    AadPreAuthentication: Application Proxy redirects users to sign in with Microsoft Entra ID, which authenticates their permissions for the directory and application.
    We recommend keeping this option as the default, so that you can take advantage of Microsoft Entra ID security features like conditional access and multifactor authentication.
    Pass through: Users don't have to authenticate against Microsoft Entra ID to access the application.
    You can still set up authentication requirements on the backend.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: AadPreAuthentication, Passthru
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ExternalUrl
  isRequired: true
  description: |+
    The address your users go to in order to access the app from outside your network.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: InternalUrl
  isRequired: true
  description: |+
    The URL that you use to access the application from inside your private network.
    You can provide a specific path on the backend server to publish, while the rest of the server is unpublished.
    In this way, you can publish different sites on the same server as different apps, and give each one its own name and access rules.
    If you publish a path, make sure that it includes all the necessary images, scripts, and style sheets for your application.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsHttpOnlyCookieEnabled
  description: |+
    Yes allows application proxy to include the HTTPOnly flag in HTTP response headers. This flag provides extra security benefits, for example, it prevents client-side scripting (CSS) from copying or modifying the cookies.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsPersistentCookieEnabled
  description: |+
    Yes allows application proxy to set its access cookies to not expire when the web browser is closed. The persistence lasts until the access token expires, or until the user manually deletes the persistent cookies.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsSecureCookieEnabled
  description: |+
    Yes allows application proxy to include the Secure flag in HTTP response headers. Secure Cookies enhances security by transmitting cookies over a TLS secured channel such as HTTPS. TLS prevents cookie transmission in clear text.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsTranslateHostHeaderEnabled
  description: |+
    If set to true, translates urls in headers.
    Keep this value true unless your application required the original host header in the authentication request.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsTranslateLinksInBodyEnabled
  description: |+
    If set to true, translates urls in body.
    Keep this value as No unless your hardcode HTML links to other on-premises applications, and don't use custom domains.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.New-EntraApplicationProxyApplication
name: New-EntraApplicationProxyApplication
description: |-
  The New-EntraApplicationProxyApplication cmdlet creates a new application configured for Application Proxy in Microsoft Entra ID.
  To ensure this application is usable, also make sure you assign users and configure SSO if needed.
  Without specifying a ConnectorGroupId, this application by default uses the Default connector group in your tenant.
metadata:
  title: New-EntraApplicationProxyApplication
  description: This article provides details on the New-EntraApplicationProxyApplication command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/26/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
