### YamlMime:PowershellCmdlet
summary: |-
  The New-EntraApplicationProxyConnectorGroup cmdlet creates a new Application Proxy Connector group.
module: Microsoft.Graph.Entra.New-EntraApplicationProxyConnectorGroup
notes: ""
inputs:
- name: <xref href="Microsoft.Open.MSGraph.Model.Name" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  New-EntraApplicationProxyConnectorGroup 
   -Name <Name> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Create a new Connector Group'
  code: |-
    PS C:\> New-EntraApplicationProxyConnectorGroup -Name "Backup Application Servers"

    Id                                   Name                       ConnectorGroupType IsDefault
    --                                   ----                       ------------------ ---------
    d533d7b1-fd92-49e8-a200-3e7dcf7c2ab5 Backup Application Servers applicationProxy       False
  description: |-
    This example demonstrated how to create a new Connector Group with the name "Backup Application Servers"
  summary: ""
parameters:
- type: <xref href="Name" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    The name of the new Connector Group.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.New-EntraApplicationProxyConnectorGroup.
name: New-EntraApplicationProxyConnectorGroup.
description: |-
  The New-EntraApplicationProxyConnectorGroup cmdlet creates a new Application Proxy connector group.
metadata:
  title: New-EntraApplicationProxyConnectorGroup.
  description: This article provides details on the New-EntraApplicationProxyConnectorGroup Command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/28/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
