### YamlMime:PowershellCmdlet
summary: |-
  Creates a key credential for an application.
module: Microsoft.Graph.Entra
notes: ""
links:
- text: Get-EntraApplication
  href: Get-EntraApplication.yml
- text: Get-EntraApplicationKeyCredential
  href: Get-EntraApplicationKeyCredential.yml
- text: Remove-EntraApplicationKeyCredential
  href: Remove-EntraApplicationKeyCredential.yml
- text: 'This cmdlet uses the ADAL library in Microsoft Entra ID. To learn more about ADAL, please follow this link:'
  href: https://www.cloudidentity.com/blog/2013/09/12/active-directory-authentication-library-adal-v1-for-net-general-availability/
syntaxes:
- >-
  New-EntraApplicationKeyCredential 
   -ObjectId <String>
   [-CustomKeyIdentifier <String>] 
   [-Type <KeyType>] 
   [-Usage <KeyUsage>]
   [-Value <String>] 
   [-EndDate <DateTime>] 
   [-StartDate <DateTime>]
   [<CommonParameters>]
examples:
- title: 'Example 1: Create a new application key credential'
  code: |-
    PS C:\> $AppID = (Get-EntraApplication -Top 1).Objectid
    PS C:\> New-EntraApplicationKeyCredential -ObjectId $AppId -CustomKeyIdentifier "Test" -StartDate "11/7/2016" -Type "Symmetric" -Usage "Sign" -Value "123"

    CustomKeyIdentifier : {84, 101, 115, 116}
    EndDate             : 11/7/2017 12:00:00 AM
    KeyId               : a5845538-3f67-402d-a03e-36d768f1441e
    StartDate           : 11/7/2016 12:00:00 AM
    Type                : Symmetric
    Usage               : Sign
    Value               : {49, 50, 51}
  description: |-
    The first command gets the ID of an application by using the [Get-EntraApplication](./Get-EntraApplication.yml) cmdlet.
    The command stores it in the $AppId variable.  

    The second command creates the application key credential for the application identified by $AppId.
  summary: ""
- title: 'Example 2: Use a certificate to add an application key credential'
  code: |-
    PS C:\> $cer = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2 #create a new certificate object
    PS C:\> $cer.Import("C:\Users\PFuller\Desktop\abc.cer") 
    PS C:\> $bin = $cer.GetRawCertData()
    PS C:\> $base64Value = [System.Convert]::ToBase64String($bin)
    PS C:\> $bin = $cer.GetCertHash()
    PS C:\> $base64Thumbprint = [System.Convert]::ToBase64String($bin)
    PS C:\> $keyid = [System.Guid]::NewGuid().ToString() 
    PS C:\> New-EntraApplicationKeyCredential -ObjectId 009d786a-3503-4217-b8ab-db03d71c179a -CustomKeyIdentifier  $base64Thumbprint  -Type AsymmetricX509Cert -Usage Verify -Value $base64Value  -StartDate $cer.GetEffectiveDateString() -EndDate cer.GetExpirationDateString()
  description: |-
    The first seven commands create values for the application key credential and store them in variables.  

    The final command uses a certificate to add an application key credential.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CustomKeyIdentifier
  description: |+
    Specifies a custom key ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: EndDate
  description: |+
    Specifies the time when the key becomes invalid as a DateTime object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies a unique ID of an application in Microsoft Entra ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: StartDate
  description: |+
    Specifies the time when the key becomes valid as a DateTime object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="KeyType" data-throw-if-not-resolved="False" />
  name: Type
  description: |+
    Specifies the type of the key.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="KeyUsage" data-throw-if-not-resolved="False" />
  name: Usage
  description: |+
    Specifies the key usage.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Value
  description: |+
    Specifies the value for the key.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.New-EntraApplicationKeyCredential
name: New-EntraApplicationKeyCredential
description: |-
  The New-EntraApplicationKeyCredential cmdlet creates a key credential for an application.
metadata:
  title: New-EntraApplicationKeyCredential
  description: This article provides details on the New-EntraApplicationKeyCredential command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/21/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
