### YamlMime:PowershellCmdlet
summary: |-
  Creates an application extension property.
module: Microsoft.Graph.Entra
notes: ""
links:
- text: Get-EntraApplicationExtensionProperty
  href: Get-EntraApplicationExtensionProperty.yml
- text: Remove-EntraApplicationExtensionProperty
  href: Remove-EntraApplicationExtensionProperty.yml
syntaxes:
- >-
  New-EntraApplicationExtensionProperty 
   -ObjectId <String> 
   -Name <String>
   [-DataType <String>]     
   [-TargetObjects <System.Collections.Generic.List`1[System.String]>] 
   [<CommonParameters>]
examples:
- title: 'Example 1: Create an extension property'
  code: |-
    PS C:\>New-EntraApplicationExtensionProperty -ObjectID "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -Name "NewAttribute"

    DeletedDateTime Id                                   AppDisplayName  DataType IsSyncedFromOnPremises Name                                                    TargetObjects
    --------------- --                                   --------------  -------- ---------------------- ----                                                    -------------
                    d083d12d-c280-4a23-a644-b4e71a09a4cb my new test app String   False                  extension_ec5edf3fe79749dd8d1e7760a1c1c943_NewAttribute {}
  description: |-
    This command creates an application extension property of the string type for the specified object.
  summary: ""
- title: 'Example 2: Create an extension property with data type parameter'
  code: |-
    PS C:\>New-EntraApplicationExtensionProperty -ObjectID "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -Name "NewAttribute" -DataType "boolean"

    DeletedDateTime Id                                   AppDisplayName  DataType IsSyncedFromOnPremises Name                                                    TargetObjects
    --------------- --                                   --------------  -------- ---------------------- ----                                                    -------------
                    d083d12d-c280-4a23-a644-b4e71a09a4cb my new test app Boolean  False                  extension_ec5edf3fe79749dd8d1e7760a1c1c943_NewAttribute {}
  description: |-
    This command creates an application extension property of the specified data type for the specified object.
  summary: ""
- title: 'Example 3: Create an extension property with targets parameter'
  code: |-
    PS C:\>$targets = New-Object System.Collections.Generic.List[System.String]
    PS C:\>$targets.Add('User')
    PS C:\>New-EntraApplicationExtensionProperty -ObjectID "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -Name "NewAttribute" -TargetObjects $targets

    DeletedDateTime Id                                   AppDisplayName  DataType IsSyncedFromOnPremises Name                                                    TargetObjects
    --------------- --                                   --------------  -------- ---------------------- ----                                                    -------------
                    d083d12d-c280-4a23-a644-b4e71a09a4cb my new test app String   False                  extension_ec5edf3fe79749dd8d1e7760a1c1c943_NewAttribute {User}
  description: |-
    The first command initializes new generic string list collection.  

    The second command adds an item to the list.  

    The final command creates an application extension property with the specified target objects for the specified object.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DataType
  description: |+
    Specifies the data type of the extension property.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies the data type of the extension property.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies a unique ID of an application in Microsoft Entra ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: TargetObjects
  description: |+
    Specifies target objects.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.New-EntraApplicationExtensionProperty
name: New-EntraApplicationExtensionProperty
description: |-
  The New-EntraApplicationExtensionProperty cmdlet creates an application extension property for an object in Microsoft Entra ID.
metadata:
  title: New-EntraApplicationExtensionProperty
  description: This article provides details on the New-EntraApplicationExtensionProperty command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/21/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
