### YamlMime:PowershellCmdlet
summary: |-
  Removes a key from an application.
module: Microsoft.Graph.Entra.Remove-EntraMSApplicationKey
notes: ""
inputs:
- name: <xref href="string" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-EntraMSApplicationKey
  href: New-EntraMSApplicationKey.yml
syntaxes:
- >-
  Remove-EntraMSApplicationKey 
   -ObjectId <String> 
   [-Proof <String>] 
   [-KeyId <String>] 
   [<CommonParameters>]
examples:
- title: 'Example 1: Removes a key credential from an application'
  code: |-
    PS C:\>Remove-EntraMSApplicationKey -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -KeyId "FDA27CF-1B58-4CAE-8CE7-CD04F0AAB945" -Proof {token}
  description: |-
    This command removes the specificed key credential from the specified application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: KeyId
  description: |+
    The key id corresponding to the key object to be removed.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique identifier of the object specific Microsoft Entra ID object

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Proof
  description: |+
    The JWT token provided as a proof of possession.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Remove-EntraMSApplicationKey.
name: Remove-EntraMSApplicationKey.
description: |-
  Removes a key from an application.
metadata:
  title: Remove-EntraMSApplicationKey.
  description: This article provides details on the Remove-EntraMSApplicationKey command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/18/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
