### YamlMime:PowershellCmdlet
summary: |-
  Delete an application by ObjectId.
module: Microsoft.Graph.Entra
notes: ""
links:
- text: Get-EntraApplication
  href: Get-EntraApplication.yml
- text: New-EntraApplication
  href: New-EntraApplication.yml
- text: Set-EntraApplication
  href: Set-EntraApplication.yml
syntaxes:
- >-
  Remove-EntraApplication 
   -ObjectId <String>
   [<CommonParameters>]
examples:
- title: 'Example 1: Remove an application'
  code: |-
    PS C:\>Remove-EntraApplication -ObjectId "acd10942-5747-4385-8824-4c5d5fa904f9"
  description: |-
    This command removes the specified application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of an application in Microsoft Entra ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Remove-EntraApplication
name: Remove-EntraApplication
description: |-
  The Remove-EntraApplication cmdlet removes the specified application from Microsoft Entra ID.
metadata:
  title: Remove-EntraApplication
  description: This article provides details on the Remove-EntraApplication command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/05/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
