### YamlMime:PowershellCmdlet
summary: |-
  Deletes an extension property from an application object.
module: Microsoft.Graph.Entra.Remove-EntraMSApplicationExtensionProperty
notes: ""
inputs:
- name: <xref href="String" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-EntraMSApplicationExtensionProperty
  href: Get-EntraMSApplicationExtensionProperty.yml
- text: New-EntraMSApplicationExtensionProperty
  href: New-EntraMSApplicationExtensionProperty.yml
syntaxes:
- >-
  Remove-EntraMSApplicationExtensionProperty 
   -ExtensionPropertyId <String> 
   -ObjectId <String>
   [<CommonParameters>]
examples:
- title: 'Example 1: Remove an extension property'
  code: |-
    PS C:\> Remove-EntraMSApplicationExtensionProperty -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -ExtensionPropertyId "344ed560-f8e7-410e-ab9f-c79df5c36"
  description: |-
    This command removes the extension property that has the specified ID from an application in Microsoft Entra ID.
    - ObjectId:  The ObjectId of the specified Application.
    - ExtensionPropertyId: The unique ID of the extension property to remove.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ExtensionPropertyId
  isRequired: true
  description: |+
    Specifies the unique ID of the extension property to remove.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the unique ID of an application in Microsoft Entra ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Remove-EntraMSApplicationExtensionProperty.
name: Remove-EntraMSApplicationExtensionProperty.
description: |-
  Deletes an extension property from an application object.
metadata:
  title: Remove-EntraMSApplicationExtensionProperty.
  description: This article provides details on the Remove-EntraMSApplicationExtensionProperty command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/18/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
