### YamlMime:PowershellCmdlet
summary: |-
  Removes a password credential from an application.
module: Microsoft.Graph.Entra.Remove-EntraApplicationPasswordCredential
notes: ""
links:
- text: Get-EntraApplication
  href: Get-EntraApplication.yml
- text: Get-EntraApplicationPasswordCredential
  href: Get-EntraApplicationPasswordCredential.yml
- text: Remove-EntraApplicationPasswordCredential
  href: Remove-EntraApplicationPasswordCredential.yml
syntaxes:
- >-
  Remove-EntraApplicationPasswordCredential 

  -ObjectId <String> 

  -KeyId <String>

  [<CommonParameters>]
examples:
- title: 'Example 1: Remove an application password credential'
  code: |-
    PS C:\> $AppID = (Get-EntraApplication -Top 1).ObjectId
    PS C:\> $KeyIDs = Get-EntraApplicationPasswordCredential -ObjectId $AppId
    PS C:\> Remove-EntraApplicationPasswordCredential -ObjectId $AppId -KeyId $KeyIds[0].KeyId
  description: |-
    The first command gets the ID of an application by using the Get-EntraApplication (./Get-EntraApplication.md) cmdlet, and then stores it in the $AppID variable.

    The second command gets the password credential for the application identified by $AppID by using the Get-EntraApplicationPasswordCredential (./ Get-EntraApplicationPasswordCredential.md) cmdlet. 
    The command stores it in the $KeyId variable.

    The final command removes the application password credential for the application identified by $AppID.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: KeyId
  isRequired: true
  description: |+
    @{Text=}

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of the application in Microsoft Entra ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Remove-EntraApplicationPasswordCredential.
name: Remove-EntraApplicationPasswordCredential.
description: |-
  The Remove-EntraApplicationPasswordCredential cmdlet removes a password credential from an application in Microsoft Entra ID.
metadata:
  title: Remove-EntraApplicationPasswordCredential.
  description: This article provides details on the Remove-EntraApplicationPasswordCredential command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/14/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
