### YamlMime:PowershellCmdlet
summary: |-
  Deletes an application object.
module: Microsoft.Graph.Entra.Remove-EntraMSApplication
notes: ""
inputs:
- name: <xref href="String" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-EntraMSApplication
  href: Get-EntraMSApplication.yml
- text: New-EntraMSApplication
  href: New-EntraMSApplication.yml
- text: Set-EntraMSApplication
  href: Set-EntraMSApplication.yml
syntaxes:
- >-
  Remove-EntraMSApplication 
   -ObjectId <String>
   [<CommonParameters>]
examples:
- title: 'Example 1: Remove an application'
  code: |-
    PS C:\>Remove-EntraMSApplication -ObjectId "acd10942-5747-4385-8824-4c5d5fa904f9"
  description: |-
    This command removes the specified application.
    - `ObjectId`:  The ObjectId of the specified application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique identifier of the object specific Microsoft Entra ID object

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Remove-EntraMSApplication.
name: Remove-EntraMSApplication.
description: |-
  Deletes an application object identified by ObjectId.
metadata:
  title: Remove-EntraMSApplication.
  description: This article provides details on the Remove-EntraMSApplication command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/14/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
