### YamlMime:PowershellCmdlet
summary: |-
  Permanently delete a recently deleted application object from deleted items.
module: Microsoft.Graph.Entra.Remove-EntraDeletedApplication
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-EntraDeletedApplication
  href: Get-EntraDeletedApplication.yml
- text: Restore-EntraDeletedApplication
  href: Restore-EntraDeletedApplication.yml
syntaxes:
- >-
  Remove-EntraDeletedApplication 
   [-ObjectId] <String> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Remove deleted application object'
  code: |-
    PS C:\> $Id = Get-EntraDeletedApplication -SearchString "newtest10" 
    PS C:\> Remove-EntraDeletedApplication -ObjectId $Id.id
  description: |-
    This command removes recently deleted application.
    - `ObjectId`:  The ObjectId of the deleted application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique identifier of deleted application.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Remove-EntraDeletedApplication.
name: Remove-EntraDeletedApplication.
description: |-
  Permanently delete a recently deleted application object from deleted items. After an item is permanently deleted, it can't be restored.
metadata:
  title: Remove-EntraDeletedApplication.
  description: This article provides details on the Remove-EntraDeletedApplication command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/16/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
