### YamlMime:PowershellCmdlet
summary: |-
  The Remove-EntraApplicationProxyApplicationConnectorGroup cmdlet sets the connector group assigned for the specified application to 'Default' and removes the current assignment.
module: Microsoft.Graph.Entra
notes: ""
syntaxes:
- >-
  Remove-EntraApplicationProxyApplicationConnectorGroup 
   -ObjectId <String> 
   [<CommonParameters>]
examples:
- title: 'Example 1:  Remove the Connector Group associated with an application.'
  code: |-
    PS C:\> Remove-EntraApplicationProxyApplicationConnectorGroup -ObjectId 59462d3c-a1bc-40a0-9bed-be799357ebce
  description: |-
    This example demonstrates how to remove the Connector Group associated with an application, setting the group to 'Default.'
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique application ID of the application.
    ObjectId can be found using the Get-EntraApplication command.
    You can also find ObjectId in the Microsoft Entra ID Portal by navigating to  Microsoft Entra ID > App registrations > All applications. Select your application. This will takes you to the application's overview page. Use the ObjectId on that page.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Remove-EntraApplicationProxyApplicationConnectorGroup
name: Remove-EntraApplicationProxyApplicationConnectorGroup
description: |-
  If your application is already in the 'Default' group, you see an error because the application can't be removed from the 'Default' group unless it's being added to another group. The application must be configured for Application Proxy in Microsoft Entra ID.
metadata:
  title: Remove-EntraApplicationProxyApplicationConnectorGroup
  description: This article provides details on the Remove-EntraApplicationProxyApplicationConnectorGroup command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/27/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
