### YamlMime:PowershellCmdlet
summary: |-
  Removes the verified publisher from an application.
module: Microsoft.Graph.Entra.Remove-EntraMSApplicationVerifiedPublisher
notes: ""
inputs:
- name: <xref href="String" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Set-EntraMSApplicationVerifiedPublisher
  href: Set-EntraMSApplicationVerifiedPublisher.yml
syntaxes:
- >-
  Remove-EntraMSApplicationVerifiedPublisher 
   -AppObjectId <String> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Remove the verified publisher from an application.'
  code: |-
    $appObjId = 'ad6c71a5-e48f-4320-bb59-92642a2d8d9f'
              Remove-EntraMSApplicationVerifiedPublisher -AppObjectId $appObjId
  description: |-
    This command demonstrates how to remove the verified publisher from an application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AppObjectId
  isRequired: true
  description: |+
    The unique identifier of a Microsoft Entra ID Application object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Remove-EntraMSApplicationVerifiedPublisher.
name: Remove-EntraMSApplicationVerifiedPublisher.
description: |-
  Removes the verified publisher from an application.
metadata:
  title: Remove-EntraMSApplicationVerifiedPublisher.
  description: This article provides details on the Remove-EntraMSApplicationVerifiedPublisher command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/25/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
