### YamlMime:PowershellCmdlet
summary: |-
  Removes an owner from an application object.
module: Microsoft.Graph.Entra.Remove-EntraMSApplicationOwner
notes: ""
inputs:
- name: <xref href="String" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-EntraMSApplicationOwner
  href: Add-EntraMSApplicationOwner.yml
- text: Get-EntraMSApplicationOwner
  href: Get-EntraMSApplicationOwner.yml
syntaxes:
- >-
  Remove-EntraMSApplicationOwner 
   -OwnerId <String> 
   -ObjectId <String> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Remove an owner from an application'
  code: |-
    PS C:\>Remove-EntraMSApplicationOwner -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -OwnerId "c13dd34a-492b-4561-b171-40fcce2916c5"
  description: |-
    This command removes the owner from the specified application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of an application in Microsoft Entra ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: OwnerId
  isRequired: true
  description: |+
    Specifies the ID of the owner.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Remove-EntraMSApplicationOwner.
name: Remove-EntraMSApplicationOwner.
description: |-
  Removes an owner from an application object.
metadata:
  title: Remove-EntraMSApplicationOwner.
  description: This article provides details on the Remove-EntraMSApplicationOwner command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/22/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
