### YamlMime:PowershellCmdlet
summary: |-
  Remove a password from an application.
module: Microsoft.Graph.Entra.Remove-EntraMSApplicationPassword
notes: ""
inputs:
- name: <xref href="string" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-EntraMSApplicationPassword
  href: New-EntraMSApplicationPassword.yml
syntaxes:
- >-
  Remove-EntraMSApplicationPassword 
   -ObjectId <String> 
   [-KeyId <String>] 
   [<CommonParameters>]
examples:
- title: 'Example 1: Removes a password from an application'
  code: |-
    PS C:\>Remove-EntraMSApplicationPassWord -ObjectId 1f88e99f-37a3-468f-80ae-e07b62ed0287 -KeyId 80e561ed-44ed-48dc-8c09-9d4803e26e4c
  description: |-
    This command remove the specified password from the specified application.  
    ObjectId: The ObjectId of the specified application.
    KeyID: The unique identifier of the PasswordCredential.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: KeyId
  description: |+
    The unique identifier for the key.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique identifier of the object specific Microsoft Entra ID object

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Remove-EntraMSApplicationPassword.
name: Remove-EntraMSApplicationPassword.
description: |-
  Remove a password from an application.
metadata:
  title: Remove-EntraMSApplicationPassword.
  description: This article provides details on the Remove-EntraMSApplicationPassword command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/25/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
