### YamlMime:PowershellCmdlet
summary: |-
  Removes a key credential from an application.
module: Microsoft.Graph.Entra.Remove-EntraApplicationKeyCredential
notes: ""
links:
- text: Get-EntraApplicationKeyCredential
  href: Get-EntraApplicationKeyCredential.yml
- text: New-EntraApplicationKeyCredential
  href: New-EntraApplicationKeyCredential.yml
syntaxes:
- >-
  Remove-EntraApplicationKeyCredential
   -ObjectId <String> 
   -KeyId <String> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Remove a key credential'
  code: |-
    PS C:\> Remove-EntraApplicationKeyCredential -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -KeyId "6aa971c6-3040-45df-87ed-581c8c09ff2b"
  description: |-
    This command removes the specified key credential from the specified application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: KeyId
  isRequired: true
  description: |+
    Specifies a custom key ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies a unique ID of an application in Microsoft Entra ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Remove-EntraApplicationKeyCredential.
name: Remove-EntraApplicationKeyCredential.
description: |-
  The Remove-EntraApplicationKeyCredential cmdlet removes a key credential from an application.
metadata:
  title: Remove-EntraApplicationKeyCredential.
  description: This article provides details on the Remove-EntraApplicationKeyCredential command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/15/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
