### YamlMime:PowershellCmdlet
summary: |-
  Updates an application.
module: Microsoft.Graph.Entra
notes: ""
links:
- text: Get-EntraApplication
  href: Get-EntraApplication.yml
- text: New-EntraApplication
  href: New-EntraApplication.yml
- text: Remove-EntraApplication
  href: Remove-EntraApplication.yml
syntaxes:
- >-
  Set-EntraApplication 
   -ObjectId <String> 
   [-PublisherDomain <String>] 
   [-OptionalClaims <OptionalClaims>]
   [-ErrorUrl <String>] 
   [-AppRoles <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.AppRole]>]
   [-Homepage <String>] 
   [-IsDisabled <Boolean>] 
   [-AvailableToOtherTenants <Boolean>]
   [-Oauth2AllowImplicitFlow <Boolean>] 
   [-InformationalUrls <InformationalUrl>] 
   [-SamlMetadataUrl <String>]
   [-PublicClient <Boolean>] 
   [-LogoutUrl <String>]
   [-RequiredResourceAccess <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.RequiredResourceAccess]>]
   [-Oauth2Permissions <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.OAuth2Permission]>]
   [-ReplyUrls <System.Collections.Generic.List`1[System.String]>] 
   [-GroupMembershipClaims <String>]
   [-IdentifierUris <System.Collections.Generic.List`1[System.String]>] 
   [-IsDeviceOnlyAuthSupported <Boolean>]
   [-AppLogoUrl <String>] 
   [-WwwHomepage <String>]
   [-OrgRestrictions <System.Collections.Generic.List`1[System.String]>]
   [-PasswordCredentials <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.PasswordCredential]>]
   [-Oauth2AllowUrlPathMatching <Boolean>]
   [-PreAuthorizedApplications <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.PreAuthorizedApplication]>]
   [-ParentalControlSettings <ParentalControlSettings>] 
   [-DisplayName <String>]
   [-Oauth2RequirePostResponse <Boolean>] 
   [-AllowGuestsSignIn <Boolean>]
   [-KeyCredentials <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.KeyCredential]>]
   [-SignInAudience <String>] 
   [-AddIns <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.AddIn]>]
   [-KnownClientApplications <System.Collections.Generic.List`1[System.String]>]
   [-RecordConsentConditions <String>] 
   [-AllowPassthroughUsers <Boolean>] 
   [<CommonParameters>]
examples:
- title: 'Example 1: Update display name of an application'
  code: |-
    PS C:\>Set-EntraApplication -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -DisplayName "New Name"
  description: |-
    This command updates the display name of the specified application.
  summary: ""
- title: 'Example 2: Update saml metadata url of an application'
  code: |-
    PS C:\>Set-EntraApplication -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -SamlMetadataUrl 'https://contoso.com'
  description: |-
    This command updates the saml metadata url of the specified application.
  summary: ""
- title: 'Example 3: Update log out url of an application'
  code: |-
    PS C:\>Set-EntraApplication -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -LogoutUrl 'https://contoso.com/Security/ADFS.aspx/logout'
  description: |-
    This command updates the log out url of the specified application.
  summary: ""
- title: 'Example 4: Update group membership claims of an application'
  code: |-
    PS C:\>Set-EntraApplication -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -GroupMembershipClaims '2'
  description: |-
    This command updates the group membership claims of the specified application.
  summary: ""
- title: 'Example 5: Update identifier uris of an application'
  code: |-
    PS C:\>Set-EntraApplication -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -IdentifierUris "https://demomail.contoso.com"
  description: |-
    This command updates the identifier uris of the specified application.
  summary: ""
parameters:
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.AddIn" data-throw-if-not-resolved="False" /><span>]</span>
  name: AddIns
  description: |+
    Defines custom behavior that a consuming service can use to call an app in specific contexts.
    For example, applications that can render file streams might set the addIns property for its "FileHandler" functionality.
    This lets services like Office 365 call the application in the context of a document the user is working on.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowGuestsSignIn
  description: |+
    Indicate if the application accepts other IDPs or not or partially accepts.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowPassthroughUsers
  description: |+
    Indicates that the application supports pass through users who have no presence in the resource tenant.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AppLogoUrl
  description: |+
    Specifies the url for the application logo image stored in a CDN.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.AppRole" data-throw-if-not-resolved="False" /><span>]</span>
  name: AppRoles
  description: |+
    The collection of application roles that an application might declare.
    These roles can be assigned to users, groups, or service principals.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AvailableToOtherTenants
  description: |+
    True if the application is shared with other tenants; otherwise, false.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayName
  description: |+
    Specifies the display name.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ErrorUrl
  description: |+
    Specifies an error URL.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GroupMembershipClaims
  description: |+
    A bitmask that configures the "groups" claim issued in a user or OAuth 2.0 access token that the application expects.
    The bitmask values are: 0: None, 1: Security groups and Microsoft Entra ID roles, 2: Reserved, and 4: Reserved.
    Setting the bitmask to 7 gets all of the security groups, distribution groups, and Microsoft Entra ID directory roles that the signed-in user is a member of.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Homepage
  description: |+
    Specifies the home page.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: IdentifierUris
  description: |+
    Specifies identifier URIs.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="InformationalUrl" data-throw-if-not-resolved="False" />
  name: InformationalUrls
  description: |+
    Basic profile information of the application such as app's marketing, support, terms of service and privacy statement URLs. The terms of service and privacy statement are surfaced to users through the user consent experience.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsDeviceOnlyAuthSupported
  description: |+
    Specifies whether this application supports device authentication without a user.  
    The default is false.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsDisabled
  description: |+
    Enables or disables the application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.KeyCredential" data-throw-if-not-resolved="False" /><span>]</span>
  name: KeyCredentials
  description: |+
    Specifies key credentials.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: KnownClientApplications
  description: |+
    Specifies known client applications.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: LogoutUrl
  description: |+
    Specifies the logout URL.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Oauth2AllowImplicitFlow
  description: |+
    Specifies whether this web application can request OAuth2.0 implicit flow tokens.
    The default is false.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Oauth2AllowUrlPathMatching
  description: |+
    Specifies whether, as part of OAuth 2.0 token requests, Microsoft Entra ID allows path matching of the redirect URI against the application's replyUrls.
    The default is false.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.OAuth2Permission" data-throw-if-not-resolved="False" /><span>]</span>
  name: Oauth2Permissions
  description: |+
    The collection of OAuth 2.0 permission scopes that the web API (resource) application exposes to client applications.
    These permission scopes might be granted to client applications during consent.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Oauth2RequirePostResponse
  description: |+
    Specifies whether, as part of OAuth 2.0 token requests, Microsoft Entra ID allows POST requests, as opposed to GET requests.  
    The default is false, which specifies that only GET requests is allowed.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of an application in Microsoft Entra ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="OptionalClaims" data-throw-if-not-resolved="False" />
  name: OptionalClaims
  description: |+
    Application developers can configure optional claims in their Microsoft Entra ID apps to specify which claims they want in tokens sent to their application by the Microsoft security token service.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: OrgRestrictions
  description: |+
    Specifies a list of tenants allowed to access application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ParentalControlSettings" data-throw-if-not-resolved="False" />
  name: ParentalControlSettings
  description: |+
    Specifies parental control settings for an application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.PasswordCredential" data-throw-if-not-resolved="False" /><span>]</span>
  name: PasswordCredentials
  description: |+
    Specifies password credentials.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.PreAuthorizedApplication" data-throw-if-not-resolved="False" /><span>]</span>
  name: PreAuthorizedApplications
  description: |+
    Sets list of pre-authorized applications.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: PublicClient
  description: |+
    Specifies whether this application is a public client (such as an installed application running on a mobile device).
    Default is false.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PublisherDomain
  description: |+
    Sets reliable domain, which can be used to identify an application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: RecordConsentConditions
  description: |+
    Don't use.
    Might be removed in future versions.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: ReplyUrls
  description: |+
    Specifies the URLs that user tokens are sent to for sign in, or the redirect URIs that OAuth 2.0 authorization codes and access tokens are sent to.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.RequiredResourceAccess" data-throw-if-not-resolved="False" /><span>]</span>
  name: RequiredResourceAccess
  description: |+
    Specifies resources that this application requires access to and the set of OAuth permission scopes and application roles that it needs under each of those resources. This pre-configuration of required resource access drives the consent experience.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SamlMetadataUrl
  description: |+
    Specifies URL to the SAML metadata for the application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SignInAudience
  description: |+
    Sets audience for signing in to the application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: WwwHomepage
  description: |+
    Sets the primary Web page.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Set-EntraApplication
name: Set-EntraApplication
description: |-
  Updates an application.
metadata:
  title: Set-EntraApplication
  description: This article provides details on the Set-EntraApplication command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/15/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
