### YamlMime:PowershellCmdlet
summary: |-
  Modifies the directory synchronization settings.
module: Microsoft.Graph.Entra
notes: ""
inputs:
- name: <xref href="System.UInt32" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.Guid" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-EntraDirSyncConfiguration
  href: Get-EntraDirSyncConfiguration.yml
syntaxes:
- >-
  Set-EntraDirSyncConfiguration 
   -AccidentalDeletionThreshold <UInt32>
   [-Force]
   [-TenantId <Guid>]
   [<CommonParameters>]
examples:
- title: 'Example 1: Set directory synchronization settings'
  code: |-
    PS C:\> Set-EntraDirSyncConfiguration -AccidentalDeletionThreshold 600 -Force
  description: |-
    This command sets directory synchronization settings.
  summary: ""
- title: 'Example 2: Set directory synchronization settings by TenantId'
  code: |-
    PS C:\> Set-EntraDirSyncConfiguration -AccidentalDeletionThreshold 600 -TenantId "d5aec55f-2d12-4442-8d2f-ccca95d4390e" -Force
  description: |-
    This command sets directory synchronization settings by TenantId.
  summary: ""
parameters:
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: AccidentalDeletionThreshold
  isRequired: true
  description: |+
    Specifies the accidental deletion threshold.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Forces the command to run without asking for user confirmation.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: TenantId
  description: |+
    Specifies the unique ID of the tenant on which to perform the operation. The default value is the tenant of the current user. This parameter applies only to partner users.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Set-EntraDirSyncConfiguration
name: Set-EntraDirSyncConfiguration
description: |-
  The Set-EntraDirSyncConfiguration cmdlet modifies the directory synchronization settings.
metadata:
  title: Set-EntraDirSyncConfiguration
  description: This article provides details on the Set-EntraDirSyncConfiguration command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/28/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
