### YamlMime:PowershellCmdlet
summary: |-
  The Set-EntraApplicationProxyConnector cmdlet allows reassignment of the connector to another connector group.
module: Microsoft.Graph.Entra
notes: |-
  ## RELATED LINKS
syntaxes:
- >-
  Set-EntraApplicationProxyConnector
   -Id <String>
   -ConnectorGroupId <String>
   [<CommonParameters>]
examples:
- title: 'Example 1: Move a Connector to a different Connector Group'
  code: |-
    PS C:\> Set-EntraApplicationProxyConnector -Id 834c5dd6-f2e8-47ae-973a-9fc769289b3d -ConnectorGroupId a39b9095-8dc8-4d3a-86c3-e7b5c3f0fb84
  description: |-
    This command moves a Connector to a different Connector Group.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ConnectorGroupId
  isRequired: true
  description: |+
    The unique identifer of the target application proxy connector group in Microsoft Entra ID.
    You can find this value using the [Get-EntraApplicationProxyConnectorGroup](./Get-EntraApplicationProxyConnectorGroup.yml) command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    The ID of the Connector being moved.
    You can find this value using the [Get-EntraApplicationProxyConnector](./Get-EntraApplicationProxyConnector.yml) command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Set-EntraApplicationProxyConnector
name: Set-EntraApplicationProxyConnector
description: |-
  The Set-EntraApplicationProxyConnector cmdlet allows reassignment of the connector to another connector group.
metadata:
  title: Set-EntraApplicationProxyConnector
  description: This article provides details on the Set-EntraApplicationProxyConnector command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/28/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
