### YamlMime:PowershellCmdlet
summary: |-
  The Set-EntraApplicationProxyApplicationCustomDomainCertificate cmdlet assigns a certificate to an application configured for Application Proxy in Microsoft Entra ID.
  This uploads the certificate and allows the application to use Custom Domains.
module: Microsoft.Graph.Entra
notes: |-
  ## RELATED LINKS
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.Security.SecureString" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Set-EntraApplicationProxyApplicationCustomDomainCertificate
   -ObjectId <String>
   -PfxFilePath <String>
   -Password <SecureString>
   [<CommonParameters>]
examples:
- title: 'Example 1: Assign a certificate to an application configured for Application Proxy'
  code: |-
    PS C:\> $securePassword = Read-Host -AsSecureString
    PS C:\> Set-EntraApplicationProxyApplicationCustomDomainCertificate -ObjectId 4eba5342-8d17-4eac-a1f6-62a0de26311e -PfxFilePath "C:\Temp\Certificates\cert.pfx" -Password $securePassword
  description: |-
    This command assigns a certificate to an application configured for Application Proxy.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique application ID for the application the certificate should be uploaded to.
    This can be found using the [Get-EntraApplication](./Get-EntraApplication.yml) command.
    You can also find this in the Azure portal by navigating to AAD, Enterprise Applications, All Applications, Select your application, go to the properties tab, and use the ObjectId on that page.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SecureString" data-throw-if-not-resolved="False" />
  name: Password
  isRequired: true
  description: |+
    A secure string containing the password for the pfx certificate

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PfxFilePath
  isRequired: true
  description: |+
    The file path for the pfx certificate for the custom domain

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Set-EntraApplicationProxyApplicationCustomDomainCertificate
name: Set-EntraApplicationProxyApplicationCustomDomainCertificate
description: |-
  The Set-EntraApplicationProxyApplicationCustomDomainCertificate cmdlet assigns a certificate to an application configured for Application Proxy in Microsoft Entra ID.
  This uploads the certificate and allows the application to use Custom Domains.
  If you have one certificate that includes many of your applications, you only need to upload it with one application and are assigned to the other relevant applications.
metadata:
  title: Set-EntraApplicationProxyApplicationCustomDomainCertificate
  description: This article provides details on the Set-EntraApplicationProxyApplicationCustomDomainCertificate command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/27/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
