### YamlMime:PowershellCmdlet
summary: |-
  Sets the verified publisher of an application to a verified Microsoft Partner Network (MPN) identifier.
module: Microsoft.Graph.Entra
notes: ""
inputs:
- name: <xref href="String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="String" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Remove-EntraMSApplicationVerifiedPublisher
  href: Remove-EntraMSApplicationVerifiedPublisher.yml
syntaxes:
- >-
  Set-EntraMSApplicationVerifiedPublisher 
   -AppObjectId <String>
   -SetVerifiedPublisherRequest <SetVerifiedPublisherRequest> 
   [<CommonParameters>]
examples:
- title: 'Example 1: Set the verified publisher of an application.'
  code: |-
    PS C:\> $appObjId = 'ad6c71a5-e48f-4320-bb59-92642a2d8d9f'
    PS C:\> $mpnId =  '0433167'
    PS C:\> $req =  @{verifiedPublisherId=$mpnId}
    PS C:\> Set-EntraMSApplicationVerifiedPublisher -AppObjectId $appObjId -SetVerifiedPublisherRequest $req
  description: |-
    This command sets the verified publisher of an application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AppObjectId
  isRequired: true
  description: |+
    The unique identifier of a Microsoft Entra ID Application object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SetVerifiedPublisherRequest" data-throw-if-not-resolved="False" />
  name: SetVerifiedPublisherRequest
  isRequired: true
  description: |+
    A request body object containing the verifiedPublisherId property it's the MPNID value.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Set-EntraMSApplicationVerifiedPublisher
name: Set-EntraMSApplicationVerifiedPublisher
description: |-
  Sets the verified publisher of an application to a verified Microsoft Partner Network (MPN) identifier.
metadata:
  title: Set-EntraMSApplicationVerifiedPublisher
  description: This article provides details on the Set-EntraMSApplicationVerifiedPublisher command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/25/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
