### YamlMime:PowershellCmdlet
summary: |-
  Updates the properties of an application object.
module: Microsoft.Graph.Entra
notes: ""
inputs:
- name: <xref href="Boolean" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.ApiApplication" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.InformationalUrl" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.OptionalClaims" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.ParentalControlSettings" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.PublicClientApplication" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.WebApplication" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.Add-in" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.AppRole" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.KeyCredential" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.PasswordCredential" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.RequiredResourceAccess" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
- name: <xref href="System.Nullable`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.Boolean" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
links:
- text: Get-EntraMSApplication
  href: Get-EntraMSApplication.yml
- text: New-EntraMSApplication
  href: New-EntraMSApplication.yml
- text: Remove-EntraMSApplication
  href: Remove-EntraMSApplication.yml
syntaxes:
- >-
  Set-EntraMSApplication 
   -ObjectId <String> 
   [-PasswordCredentials <System.Collections.Generic.List`1[Microsoft.Open.MSGraph.Model.PasswordCredential]>]
   [-TokenEncryptionKeyId <String>] 
   [-SignInAudience <String>]
   [-KeyCredentials <System.Collections.Generic.List`1[Microsoft.Open.MSGraph.Model.KeyCredential]>]
   [-ParentalControlSettings <ParentalControlSettings>]
   [-IdentifierUris <System.Collections.Generic.List`1[System.String]>]
   [-AppRoles <System.Collections.Generic.List`1[Microsoft.Open.MSGraph.Model.AppRole]>]
   [-PublicClient <PublicClientApplication>] 
   [-InformationalUrl <InformationalUrl>] 
   [-Tags <System.Collections.Generic.List`1[System.String]>] 
   [-Api <ApiApplication>]
   [-OptionalClaims <OptionalClaims>] 
   [-GroupMembershipClaims <String>] 
   [-Web <WebApplication>]
   [-DisplayName <String>] 
   [-IsFallbackPublicClient <Boolean>] 
   [-IsDeviceOnlyAuthSupported <Boolean>]
   [-RequiredResourceAccess <System.Collections.Generic.List`1[Microsoft.Open.MSGraph.Model.RequiredResourceAccess]>]
   [<CommonParameters>]
examples:
- title: 'Example 1: Update an application'
  code: |-
    PS C:\> Set-EntraMSApplication -ObjectId fcd37fb8-449c-45af-92fc-5448c671fd30 -DisplayName "My new application"
  description: |-
    This command updates an application in Microsoft Entra ID.
  summary: ""
- title: 'Example 2: Update an application using IdentifierUris parameter'
  code: |-
    PS C:\> Set-EntraMSApplication -ObjectId fcd37fb8-449c-45af-92fc-5448c671fd30 -IdentifierUris "https://mynewapp.contoso.com"
  description: |-
    This command updates an application in Microsoft Entra ID.
  summary: ""
- title: 'Example 3: Update an application using GroupMembershipClaims parameter'
  code: |-
    PS C:\> Set-EntraMSApplication -ObjectId fcd37fb8-449c-45af-92fc-5448c671fd30 -GroupMembershipClaims "SecurityGroup"
  description: |-
    This command updates an application in Microsoft Entra ID.
  summary: ""
- title: 'Example 4: Update an application using IsDeviceOnlyAuthSupported parameter'
  code: |-
    PS C:\> Set-EntraMSApplication -ObjectId fcd37fb8-449c-45af-92fc-5448c671fd30 -IsDeviceOnlyAuthSupported $false
  description: |-
    This command updates an application in Microsoft Entra ID.
  summary: ""
- title: 'Example 5: Update an application using Tags parameter'
  code: |-
    PS C:\> Set-EntraMSApplication -ObjectId fcd37fb8-449c-45af-92fc-5448c671fd30 -Tags "mytag"
  description: |-
    This command updates an application in Microsoft Entra ID.
  summary: ""
parameters:
- type: <xref href="ApiApplication" data-throw-if-not-resolved="False" />
  name: Api
  description: |+
    Specifies settings for an application that implements a web API.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.AppRole" data-throw-if-not-resolved="False" /><span>]</span>
  name: AppRoles
  description: |+
    The collection of application roles that an application might declare.
    These roles can be assigned to users, groups, or service principals.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayName
  description: |+
    Specifies the display name.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GroupMembershipClaims
  description: |+
    Configures the groups claim issued in a user or OAuth 2.0 access token that the application expects.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: IdentifierUris
  description: |+
    Specifies identifier URIs.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="InformationalUrl" data-throw-if-not-resolved="False" />
  name: InformationalUrl
  description: |+
    Basic profile information of the application such as app's marketing, support, terms of service and privacy statement URLs.
    The terms of service and privacy statement are surfaced to users through the user consent experience.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsDeviceOnlyAuthSupported
  description: |+
    Specifies if the application supports authentication using a device token.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsFallbackPublicClient
  description: |+
    Specifies the fallback application type as public client, such as an installed application running on a mobile device.
    The default value is false that means the fallback application type is confidential client such as web app.
    There are certain scenarios where Microsoft Entra ID can't determine the client application type (for example,
    ROPC flow where it's configured without specifying a redirect URI).
    In those cases Microsoft Entra ID interprets the application type based on the value of this property.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.KeyCredential" data-throw-if-not-resolved="False" /><span>]</span>
  name: KeyCredentials
  description: |+
    Specifies key credentials.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of an application in Microsoft Entra ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="OptionalClaims" data-throw-if-not-resolved="False" />
  name: OptionalClaims
  description: |+
    Application developers can configure optional claims in their Microsoft Entra ID apps to specify which claims they want in tokens sent to their application by the Microsoft security token service.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ParentalControlSettings" data-throw-if-not-resolved="False" />
  name: ParentalControlSettings
  description: |+
    Specifies parental control settings for an application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.PasswordCredential" data-throw-if-not-resolved="False" /><span>]</span>
  name: PasswordCredentials
  description: |+
    The collection of password credentials associated with the application

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PublicClientApplication" data-throw-if-not-resolved="False" />
  name: PublicClient
  description: |+
    Specifies whether this application is a public client (such as an installed application running on a mobile device).
    Default is false.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.RequiredResourceAccess" data-throw-if-not-resolved="False" /><span>]</span>
  name: RequiredResourceAccess
  description: |+
    Specifies resources that this application requires access to and the set of OAuth permission scopes and application roles that it needs under each of those resources.
    This preconfiguration of required resource access drives the consent experience.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SignInAudience
  description: |+
    Specifies what Microsoft accounts are supported for the current application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: Tags
  description: |+
    Custom strings that can be used to categorize and identify the application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TokenEncryptionKeyId
  description: |+
    Specifies the keyId of a public key from the keyCredentials collection.
    When configured, Microsoft Entra ID encrypts all the tokens it emits by using the key this property points to.
    The application code that receives the encrypted token must use the matching private key to decrypt the token before it can be used for the signed-in user.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="WebApplication" data-throw-if-not-resolved="False" />
  name: Web
  description: |+
    Specifies settings for a web application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Entra.Set-EntraMSApplication
name: Set-EntraMSApplication
description: |-
  Updates the properties of an application object.
metadata:
  title: Set-EntraMSApplication
  description: This article provides details on the Set-EntraMSApplication command.
  ms.service: active-directory
  ms.topic: reference
  ms.date: 03/25/2024
  ms.author: eunicewaweru
  ms.reviewer: stevemutungi
  manager: CelesteDG
  author: msewaweru
  external help file: Microsoft.Graph.Entra-Help.xml
  Module Name: Microsoft.Graph.Entra
  online version: ""
  PlatyPS schema version: 2.0.0
